### ISSUE TITLE
Sticker Id is mandatory

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#105]
The issue is related to:
- #104 

| Command                   | Access     | Description                                                                                                                           |
| ------------------------- | ---------- | ------------------------------------------------------------------------------------------------------------------------------------- |
| `RLE [Bots] [Sticker Id]` | `Operator` | Claim the `Redfall Launch Event` items, if not provide `Sticker Id`(from 1 to 4), will try to claim all, usually can claim 2 stickers |

---

I believe there is an error if the `[Sticker Id]` is not provided, e.g. `!rle ASF` returns:

```
<Wok> Invalid entry
```

In contrast,  `!rle ASF 1` returns:

```
<Wok> Done!
<Bot1> Done!
<Bot2> Done!
<Bot3> Done!
```

I get similar outputs as long as an id is explicitly provided.

**Comment by VladozPlay** [comment]
> The issue is related to:
> 
> * [Get items from the Redfall Hero Quiz #104](https://github.com/chr233/ASFEnhance/issues/104)
> 
> Command	Access	Description
> `RLE [Bots] [Sticker Id]`	`Operator`	Claim the `Redfall Launch Event` items, if not provide `Sticker Id`(from 1 to 4), will try to claim all, usually can claim 2 stickers
> I believe there is an error if the `[Sticker Id]` is not provided, e.g. `!rle ASF` returns:
> 
> ```
> <Wok> Invalid entry
> ```
> 
> In contrast, `!rle ASF 1` returns:
> 
> ```
> <Wok> Done!
> <Bot1> Done!
> <Bot2> Done!
> <Bot3> Done!
> ```
> 
> I get similar outputs as long as an id is explicitly provided.

I have the same error.

**Comment by chr233** [comment]
oh I see, change RLE's usage in 1.8.0.2.

**Comment by woctezuma** [comment]
Thank you!
