### ISSUE TITLE
购买礼物给他人的功能是坏掉了嘛

### ISSUE THREAD

**Issue by ECHOWIKM** [chr233/ASFEnhance#109]
之前还是好好的，最近更新了以后用PCG命令没法送礼物了，礼物额度是够的，然后手动能送，用指令送了就送不出去
ac ar23 166844
<AR23> ID：166844 | 状态：OK
c ar23
<AR23> 多行结果:
购物车总额: 329.99 ARS$
- App/620980 Beat Saber 329.99
为自己购买: √
作为礼物购买: √

pcg ar23 wsy
<AR23> 购买失败, 余额未变动

balance ar23
<AR23> 钱包余额: 477.8 ARS

<AR23> 多行结果:
商店消费记录统计:
 1.按购买类型分类(不含已退款的消费):
 - 商店购买: 2690.52 ARS$
   - 外部: 0.00 ARS$
   - 余额: 2690.52 ARS$
 - 礼物赠送: 0.00 ARS$
   - 外部: 0.00 ARS$
   - 余额: 0.00 ARS$
 - 游戏内购: 0.00 ARS$
 - 市场购买: 0.00 ARS$
 - 市场出售: 2167.63 ARS$
数据统计(仅供参考):
 - 有效额度总和: 2690.52 ARS$
 - 外部消费总和: 0.00 ARS$
 - 礼物赠送总和: 0.00 ARS$
额度推算(仅供参考):
 - 额度*1.0 - 送礼: 2690.00 ARS$
数据说明:
 - 基准汇率 ARS
 - 计算结果由 ASFEnhance 生成, 仅供参考
 - 汇率数据更新时间: 2023/5/9 0:00
 - 在线汇率数据来自 ExchangeRate-API.com

**Comment by ECHOWIKM** [comment]
chr大大我非常需要这个功能，555，最近没法送好多游戏都下架了

**Comment by chr233** [comment]
计算steamId32有点问题，更新到今天的版本可以修复，应该

**Comment by ECHOWIKM** [comment]
奥 这样子
