### ISSUE TITLE
关于查看购物车金额显示问题

### ISSUE THREAD

**Issue by Suiyi-Light** [chr233/ASFEnhance#11]
因部分地区使用逗号作为小数点，导致部分区域（如土耳其）在购物车中显示数字错误
![Screenshot_2022-04-20-16-57-26-621_com android browser](https://user-images.githubusercontent.com/69178257/164192825-faa13fcc-350f-4379-9f07-a3152ef3ff74.jpg)
希望能够修正，谢谢

**Comment by chr233** [comment]
收到，下个版本修复。

**Comment by chr233** [comment]
已修复~
