### ISSUE TITLE
用快速邀请链接加好友 Add bot friend using Quick Invite link

### ISSUE THREAD

**Issue by Megalounge** [chr233/ASFEnhance#114]
**Add bot friend using Quick Invite link / 用快速邀请链接加好友**

Some accounts don't have the ability to send friend requests using normal method, but the quick invite link allows P2P friend request, it's instant and does not require confirmation from the one being added.

the example link looks like this *https://s.team/p/****-****/nk****tp*, you will be able to find your link in the Add Friend page, I find this useful for those account who dont have access to sending friend requests.

有些人的账号无法用正常的方式加好友（比如搜索好友代码、个人主页的添加好友按钮），但是快速邀请链接可以进行点对点加好友，可以立即互相加上好友且不需要确认（缺点就是链接只能使用一次）
我个人觉得这个方法对于那些无法加好友的账号来说是很好的。请考虑添加此功能！感谢

**Comment by nepcat** [comment]
Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.

**Comment by chr233** [comment]
> Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.

can u give me more information, such as your what command u inputed

**Comment by nepcat** [comment]
> > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> 
> can u give me more information, such as your what command u inputed

i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......

**Comment by chr233** [comment]
> > > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> > 
> > 
> > can u give me more information, such as your what command u inputed
> 
> i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......

I think it works fine, I can't answer any question about steam's account limit, test on my account works.

before:
![image](https://github.com/chr233/ASFEnhance/assets/13798576/9b9e0a1b-3a3e-47f8-8fa9-0fa6185ce421)

after:
![image](https://github.com/chr233/ASFEnhance/assets/13798576/98d64ae2-43a6-43ff-9adb-937378e3612d)

command:
![image](https://github.com/chr233/ASFEnhance/assets/13798576/d80fba66-a7c8-47dc-a640-327b04d5462d)

**Comment by nepcat** [comment]
> > > > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> > > 
> > > 
> > > can u give me more information, such as your what command u inputed
> > 
> > 
> > i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......
> 
> I think it works fine, I can't answer any question about steam's account limit, test on my account works.
> 
> before: ![image](https://private-user-images.githubusercontent.com/13798576/299520433-9b9e0a1b-3a3e-47f8-8fa9-0fa6185ce421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA0MzMtOWI5ZTBhMWItM2EzZS00N2Y4LThmYTktMGZhNjE4NWNlNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjBmMzk3OWQ1YmM5NTNmOGZjYjQ3MDMwMjJjNTc2YmFiYjk3MDkyNjljOTE4M2E0OTBiNDlhMzU3OWRkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4e0AIy0F2e4E2o3bTfTEEfDJ7nImnCUCkfgVY5H6LU)
> 
> after: ![image](https://private-user-images.githubusercontent.com/13798576/299520623-98d64ae2-43a6-43ff-9adb-937378e3612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA2MjMtOThkNjRhZTItNDNhNi00M2ZmLTlhZGItOTM3Mzc4ZTM2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWIyYzFhZWRjNWJlNjUyZTFmOWNhMmRlNmUzNmE5MzAwNDUxZTI3MmNiOWQyYjhhYTYyMGI2NmZjY2M4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2grH9MaJpXn1AFG12vdFACvzwTqxwPFbBYJlqaTnYX8)
> 
> command: ![image](https://private-user-images.githubusercontent.com/13798576/299520747-d80fba66-a7c8-47dc-a640-327b04d5462d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA3NDctZDgwZmJhNjYtYTdjOC00N2RjLWE2NDAtMzI3YjA0ZDU0NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTE4NjgwMjM4MjM4OGY4M2YzMmQ4MDdjZGRhMmQwZDY4NzdhZWMwNmZkYjJlYjQ1YjZhYTc4YTFkZTY2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bc_uvdlQiGyLkg9eM9Kw-zCYEQxVCercRoEKgKxTMI)

addfriend bot1 https://s.team/p/kfp-****/HN****TG
<bot1> Get profile info failed

using latest asfenchance release

**Comment by chr233** [comment]
> > > > > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> > > > 
> > > > 
> > > > can u give me more information, such as your what command u inputed
> > > 
> > > 
> > > i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......
> > 
> > I think it works fine, I can't answer any question about steam's account limit, test on my account works.
> > 
> > before: ![image](https://private-user-images.githubusercontent.com/13798576/299520433-9b9e0a1b-3a3e-47f8-8fa9-0fa6185ce421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA0MzMtOWI5ZTBhMWItM2EzZS00N2Y4LThmYTktMGZhNjE4NWNlNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjBmMzk3OWQ1YmM5NTNmOGZjYjQ3MDMwMjJjNTc2YmFiYjk3MDkyNjljOTE4M2E0OTBiNDlhMzU3OWRkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4e0AIy0F2e4E2o3bTfTEEfDJ7nImnCUCkfgVY5H6LU)
> > 
> > after: ![image](https://private-user-images.githubusercontent.com/13798576/299520623-98d64ae2-43a6-43ff-9adb-937378e3612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA2MjMtOThkNjRhZTItNDNhNi00M2ZmLTlhZGItOTM3Mzc4ZTM2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWIyYzFhZWRjNWJlNjUyZTFmOWNhMmRlNmUzNmE5MzAwNDUxZTI3MmNiOWQyYjhhYTYyMGI2NmZjY2M4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2grH9MaJpXn1AFG12vdFACvzwTqxwPFbBYJlqaTnYX8)
> > 
> > command: ![image](https://private-user-images.githubusercontent.com/13798576/299520747-d80fba66-a7c8-47dc-a640-327b04d5462d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA3NDctZDgwZmJhNjYtYTdjOC00N2RjLWE2NDAtMzI3YjA0ZDU0NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTE4NjgwMjM4MjM4OGY4M2YzMmQ4MDdjZGRhMmQwZDY4NzdhZWMwNmZkYjJlYjQ1YjZhYTc4YTFkZTY2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bc_uvdlQiGyLkg9eM9Kw-zCYEQxVCercRoEKgKxTMI)
> 
> addfriend bot1 https://s.team/p/kfp-****/HN****TG
> <bot1> Get profile info failed
> 
> using latest asfenchance release

pls give me your invite link, send via steam or email or so

**Comment by nepcat** [comment]
> > > > > > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> > > > > 
> > > > > 
> > > > > can u give me more information, such as your what command u inputed
> > > > 
> > > > 
> > > > i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......
> > > 
> > > 
> > > I think it works fine, I can't answer any question about steam's account limit, test on my account works.
> > > before: ![image](https://private-user-images.githubusercontent.com/13798576/299520433-9b9e0a1b-3a3e-47f8-8fa9-0fa6185ce421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA0MzMtOWI5ZTBhMWItM2EzZS00N2Y4LThmYTktMGZhNjE4NWNlNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjBmMzk3OWQ1YmM5NTNmOGZjYjQ3MDMwMjJjNTc2YmFiYjk3MDkyNjljOTE4M2E0OTBiNDlhMzU3OWRkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4e0AIy0F2e4E2o3bTfTEEfDJ7nImnCUCkfgVY5H6LU)
> > > after: ![image](https://private-user-images.githubusercontent.com/13798576/299520623-98d64ae2-43a6-43ff-9adb-937378e3612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA2MjMtOThkNjRhZTItNDNhNi00M2ZmLTlhZGItOTM3Mzc4ZTM2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWIyYzFhZWRjNWJlNjUyZTFmOWNhMmRlNmUzNmE5MzAwNDUxZTI3MmNiOWQyYjhhYTYyMGI2NmZjY2M4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2grH9MaJpXn1AFG12vdFACvzwTqxwPFbBYJlqaTnYX8)
> > > command: ![image](https://private-user-images.githubusercontent.com/13798576/299520747-d80fba66-a7c8-47dc-a640-327b04d5462d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA3NDctZDgwZmJhNjYtYTdjOC00N2RjLWE2NDAtMzI3YjA0ZDU0NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTE4NjgwMjM4MjM4OGY4M2YzMmQ4MDdjZGRhMmQwZDY4NzdhZWMwNmZkYjJlYjQ1YjZhYTc4YTFkZTY2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bc_uvdlQiGyLkg9eM9Kw-zCYEQxVCercRoEKgKxTMI)
> > 
> > 
> > addfriend bot1 https://s.team/p/kfp-****/HN****TG
> >  Get profile info failed
> > using latest asfenchance release
> 
> pls give me your invite link, send via steam or email or so

sent to your email, also that account is private, maybe thats the reason why it fails?

**Comment by chr233** [comment]
> > > > > > > Hello, it it really added? i only see command to receive an invite link (s.team), but i don't see any way to use it to add every bot account (like how ADDBOTFRIEND asf does it, but it only works on unlimited steam account), and ADDFRIEND command doesn't support s.team link.
> > > > > > 
> > > > > > 
> > > > > > can u give me more information, such as your what command u inputed
> > > > > 
> > > > > 
> > > > > i got s.team friend invite link using INVITELINK command, then i tried using that link through ADDFRIEND command and it failed, this is what i used: ADDFRIEND bot_name https://s.team/.......
> > > > 
> > > > 
> > > > I think it works fine, I can't answer any question about steam's account limit, test on my account works.
> > > > before: ![image](https://private-user-images.githubusercontent.com/13798576/299520433-9b9e0a1b-3a3e-47f8-8fa9-0fa6185ce421.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA0MzMtOWI5ZTBhMWItM2EzZS00N2Y4LThmYTktMGZhNjE4NWNlNDIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMjBmMzk3OWQ1YmM5NTNmOGZjYjQ3MDMwMjJjNTc2YmFiYjk3MDkyNjljOTE4M2E0OTBiNDlhMzU3OWRkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4e0AIy0F2e4E2o3bTfTEEfDJ7nImnCUCkfgVY5H6LU)
> > > > after: ![image](https://private-user-images.githubusercontent.com/13798576/299520623-98d64ae2-43a6-43ff-9adb-937378e3612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA2MjMtOThkNjRhZTItNDNhNi00M2ZmLTlhZGItOTM3Mzc4ZTM2MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWIyYzFhZWRjNWJlNjUyZTFmOWNhMmRlNmUzNmE5MzAwNDUxZTI3MmNiOWQyYjhhYTYyMGI2NmZjY2M4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2grH9MaJpXn1AFG12vdFACvzwTqxwPFbBYJlqaTnYX8)
> > > > command: ![image](https://private-user-images.githubusercontent.com/13798576/299520747-d80fba66-a7c8-47dc-a640-327b04d5462d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYyNjcsIm5iZiI6MTcwNjE5NTk2NywicGF0aCI6Ii8xMzc5ODU3Ni8yOTk1MjA3NDctZDgwZmJhNjYtYTdjOC00N2RjLWE2NDAtMzI3YjA0ZDU0NjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZTE4NjgwMjM4MjM4OGY4M2YzMmQ4MDdjZGRhMmQwZDY4NzdhZWMwNmZkYjJlYjQ1YjZhYTc4YTFkZTY2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0bc_uvdlQiGyLkg9eM9Kw-zCYEQxVCercRoEKgKxTMI)
> > > 
> > > 
> > > addfriend bot1 https://s.team/p/kfp-****/HN****TG
> > > Get profile info failed
> > > using latest asfenchance release
> > 
> > 
> > pls give me your invite link, send via steam or email or so
> 
> sent to your email, also that account is private, maybe thats the reason why it fails?

fixed in 2.0.10.1
