### ISSUE TITLE
Shopping cart is empty and no checkout is required

### ISSUE THREAD

**Issue by Izymiro** [chr233/ASFEnhance#118]
cant sent gift to friend
![image](https://github.com/chr233/ASFEnhance/assets/71022200/a230f2d0-7bb9-4d87-95b3-c74e5e5f9b37)

**Comment by Izymiro** [comment]
![image](https://github.com/chr233/ASFEnhance/assets/71022200/9ac7479d-180a-4000-8559-e4e601624812)

**Comment by chr233** [comment]
steam has change its API maybe

**Comment by chr233** [comment]
fixed in 1.8.5.0
