### ISSUE TITLE
能否在插件内内置一个帮助列表

### ISSUE THREAD

**Issue by Mr54233** [chr233/ASFEnhance#12]
列出一个`命令-对应操作`的列表，就叫ehelp（enhancehelp

**Comment by chr233** [comment]
懒，要不你写一个

**Comment by chr233** [comment]
加了，dnmd

**Comment by Mr54233** [comment]
![image](https://user-images.githubusercontent.com/46802509/169625950-974eeb70-c1ea-4fce-afdd-116aecd0b9e3.png)
这加了啥啊

**Comment by chr233** [comment]
命令是 help xxx，xxx是命令名称，支持缩写

**Comment by Mr54233** [comment]
> 命令是 help xxx，xxx是命令名称，支持缩写

不对啊，我就是不记得命令名称啊，我要记得命令我还help个锤子

**Comment by chr233** [comment]
那你自己加呗，相关源码在 other 文件夹下

**Comment by chr233** [comment]
加了，用 au 升级即可
