### ISSUE TITLE
Get items from the Steam Summer Sale 2023 - Daily Trading Card & Sticker

### ISSUE THREAD

**Issue by Quarer** [chr233/ASFEnhance#120]
- Daily trading card (14x)
    Link: https://store.steampowered.com/explore
    You can get 1 of them per day (total of 14 free cards if you get 1 every day - resets daily at 17:00 UTC) by 

- Daily chat sticker (14x)
    Visit any sale category to claim sticker, for example: https://store.steampowered.com/greatondeck

Thanks in advance, brother.

**Comment by guihkx** [comment]
> * Daily trading card (14x)
>       Link: https://store.steampowered.com/explore
>       You can get 1 of them per day (total of 14 free cards if you get 1 every day - resets daily at 17:00 UTC) by

ASF [already does that](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#autosteamsaleevent) automatically (every 8 hours).

> * 
> 
> * Daily chat sticker (14x)
>   Visit any sale category to claim sticker, for example: https://store.steampowered.com/greatondeck

There's a command for this already: [`!CLAIMITEM`](https://github.com/chr233/ASFEnhance/blob/1.8.5.0/README.en.md#event-command).

**Comment by woctezuma** [comment]
> ASF [already does that](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#autosteamsaleevent) automatically (every 8 hours).

One can also use `!EXPLORER`.

**Comment by Enissay** [comment]
> There's a command for that already: [`!CLAIMITEM`](https://github.com/chr233/ASFEnhance/blob/1.8.5.0/README.en.md#event-command).

Not working it seems:
> \> CI mybot
<001> Unknown command!
> \> CLAIMITEM mybot
<001> Unknown command!
