### ISSUE TITLE
!EXPLORER asf not working

### ISSUE THREAD

**Issue by rezamatrix** [chr233/ASFEnhance#123]
hi 
i had problem with command  !EXPLORER asf last  day  command work  but today not working anymore
< <******> Explore discovery queue task will start immediately
and nothing in log

**Comment by rezamatrix** [comment]
< <******> Explore discovery queue task will start immediately
and nothing  in log

**Comment by woctezuma** [comment]
No problem for me.

**Comment by Enissay** [comment]
It takes some time to execute, not instant! But eventually it runs.

**Comment by rezamatrix** [comment]
the problem  is my net and steam  server  problem after 20 min everything worked

**Comment by rezamatrix** [comment]
solve
