### ISSUE TITLE
Typo with purchasegift: coasts -> costs

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#130]
After running the following command, I have noticed a typo in English: it should be `costs` instead of `coasts`.

**Command:**

```bash
!purchasegift Gifter Recipient
```

**Output:**

```
Purchase done, all coasts: 1,62€
```

**Expected output:**

```
Purchase done, all costs: 1,62€
```

**Comment by chr233** [comment]
Thanks for correction
