### ISSUE TITLE
[Feature Request] `!rmlicense` command

### ISSUE THREAD

**Issue by guihkx** [chr233/ASFEnhance#14]
Hi!

ASF provides the `!addlicense` command, so I thought it'd be interesting to have a `!rmlicense` or `!removelicense` counterpart.

This could be useful to remove licenses of demos/f2p games that we added to our account. Here's where you remove these licenses:

https://store.steampowered.com/account/licenses/

Thoughts? Thank you!

**Comment by chr233** [comment]
it seems easy to impl this future

**Comment by chr233** [comment]
Added translation
