### ISSUE TITLE
Get free items for the 20th Anniversary of Steam

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#144]
- https://store.steampowered.com/sale/steam20
- https://store.steampowered.com/points/shop/event/sale_steam20
- https://www.steamcardexchange.net/index.php?gamepage-appid-2598440

**Comment by chr233** [comment]
todo.

**Comment by chr233** [comment]
added in 1.8.11.1

**Comment by woctezuma** [comment]
Thank you!
