### ISSUE TITLE
优化一下互加好友功能

### ISSUE THREAD

**Issue by kajial** [chr233/ASFEnhance#147]
把互加好友的功能用通过好友快速链接来加好友，这样两个号没满5美元也能互相添加了

**Comment by chr233** [comment]
有命令可以生成邀请链接，也支持通过邀请链接添加好友

**Comment by kajial** [comment]
生成邀请链接的命令是哪个，我看了文档只有好友代码个人主页链接和交易链接

**Comment by chr233** [comment]
INVITELINK [Bots]
