### ISSUE TITLE
[Feature Request] ingame item drops for idled games

### ISSUE THREAD

**Issue by ksardsas2015** [chr233/ASFEnhance#15]
It would be very cool to implement the functionality of this plugin : https://github.com/Sniper677/ASF_ItemDropper (it is not working in new ASF versions). I think that only command idrop is needed

**Comment by chr233** [comment]
I will see……

**Comment by chr233** [comment]
https://github.com/chr233/ASF_ItemDropper/releases

I migrated to .net using ASF 5.2.6.3, functions not tested but seems compatible with the latest version of ASF.

I will close this issue, if any issues about ASF_ItemDropper, please comment to that repo.

**Comment by justakingalook** [comment]
The plugin seems to be working flawless, however it seems it doesnt have any delay between accounts, wich it causes to "stop" working after a few drops.

Would be possible that you fix it and add some way where it try to drop once every 24h automatically  instead of giving the proper command manually?

Btw wish to give some small donation for your amazing work, in case you accept some tf2 keys as donation please tell me back!

**Comment by chr233** [comment]
> The plugin seems to be working flawless, however it seems it doesnt have any delay between accounts, wich it causes to "stop" working after a few drops.
> 
> Would be possible that you fix it and add some way where it try to drop once every 24h automatically instead of giving the proper command manually?
> 
> Btw wish to give some small donation for your amazing work, in case you accept some tf2 keys as donation please tell me back!

https://github.com/JustArchiNET/ArchiSteamFarm/blob/772607b68006d54f2a82a17cbc27184bdea3a7f1/ArchiSteamFarm/Steam/Integration/SteamSaleEvent.cs#L45

ASF's default behavior is start explorer after 1.1 hours(if you have more than 1 bot, ASF will increase delay time), and repeat this task every 8.1 hours.

https://github.com/chr233/ASFEnhance/blob/b016e1c0a35919c6d6f1c19a493dc912c5602d77/ASFEnhance/Explorer/Command.cs#L37

Actually ASFEnhance doesn't change ASF's explorer queue logic, it just reset ASF's Timer via reflection to let ASF start explorer task immediately.

Anyway, if you want to donate, I have write my trade link in README.md, or this link:

https://steamcommunity.com/tradeoffer/new/?partner=221260487&token=xgqMgL-i

**Comment by chr233** [comment]
> The plugin seems to be working flawless, however it seems it doesnt have any delay between accounts, wich it causes to "stop" working after a few drops.
> 
> Would be possible that you fix it and add some way where it try to drop once every 24h automatically instead of giving the proper command manually?
> 
> Btw wish to give some small donation for your amazing work, in case you accept some tf2 keys as donation please tell me back!

This plugin is not written by myself, and it can be very hard to do some changes.

If you want any technical support,, i's very good to comment to that [repo](https://github.com/chr233/ASF_ItemDropper).

Anyway, if you want to donate, my trade link is: 
https://steamcommunity.com/tradeoffer/new/?partner=221260487&token=xgqMgL-i
