### ISSUE TITLE
Get items from the Shmup Fest 2023

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#150]
- https://store.steampowered.com/category/shmup
- https://steamdb.info/app/2606780/communityitems/
- https://www.steamcardexchange.net/index.php?gamepage-appid-2606780

```bash
!claimitem ASF

or

!ci ASF
```

**Comment by themojache** [comment]
https://github.com/chr233/ASFEnhance/blob/master/ASFEnhance/Event/WebRequest.cs#L107
I have not observed the Claiming Sticker Requests.
I imagine ISaleItemRewardsService still functions the same.
Odds are the referrer needs to be updated.

It looks like an old trick still works which can make this functionality more dynamic (not depend on updating the store link for each sale)... Which is to use "https://store.steampowered.com/points/shop" as the referrer.
Source: https://github.com/PotcFdk/SteamDiscoveryQueueAutoSkipper/blob/master/SteamDiscoveryQueueAutoSkipper.user.js#L239 (current line to claim_sale_reward function)

This user-script seems to work for me.

**Comment by chr233** [comment]
> ###
> **[themojache](/themojache) ** commented [Sep 26, 2023](#issuecomment-1734760426) •

So what do you mean, finish queue task to claim cards?

**Comment by themojache** [comment]
> > **[themojache](/themojache) ** commented [Sep 26, 2023](#issuecomment-1734760426) •
> 
> So what do you mean, finish queue task to claim cards?

I believe the following code offers some functional improvements compared to the current implementation of ClaimDailySticker in "ASFEnhance/ASFEnhance/Event/WebRequest.cs":
`function claim_sale_reward (webapi_token) {
	return fetch("https://api.steampowered.com/ISaleItemRewardsService/ClaimItem/v1?access_token=" + webapi_token, {
		"credentials": "omit",
		"headers": {
			"Content-Type": "multipart/form-data; boundary=---------------------------90594386426341336747734585788"
		},
		"referrer": "https://store.steampowered.com/points/shop",
		"body": "-----------------------------90594386426341336747734585788\r\nContent-Disposition: form-data; name=\"input_protobuf_encoded\"\r\n\r\n\r\n-----------------------------90594386426341336747734585788--\r\n",
		"method": "POST",
		"mode": "cors"
	});
}`

https://github.com/PotcFdk/SteamDiscoveryQueueAutoSkipper/blob/master/SteamDiscoveryQueueAutoSkipper.user.js#L297 shows the request they do to claim an item.

Does the command for "!claimitem" currently work for Shmup Fest? By this ticket I was believing it was not functional. That referrer or request seems to work for some time now, so less maintenance. :)
Either way this offers some other functionality such as the CanClaimItemResponse protobuf request.

**Comment by chr233** [comment]
> > > **[themojache](/themojache) ** commented [Sep 26, 2023](#issuecomment-1734760426) •
> > 
> > 
> > So what do you mean, finish queue task to claim cards?
> 
> I believe the following code offers some functional improvements compared to the current implementation of ClaimDailySticker in "ASFEnhance/ASFEnhance/Event/WebRequest.cs": `function claim_sale_reward (webapi_token) { return fetch("https://api.steampowered.com/ISaleItemRewardsService/ClaimItem/v1?access_token=" + webapi_token, { "credentials": "omit", "headers": { "Content-Type": "multipart/form-data; boundary=---------------------------90594386426341336747734585788" }, "referrer": "https://store.steampowered.com/points/shop", "body": "-----------------------------90594386426341336747734585788\r\nContent-Disposition: form-data; name=\"input_protobuf_encoded\"\r\n\r\n\r\n-----------------------------90594386426341336747734585788--\r\n", "method": "POST", "mode": "cors" }); }`
> 
> https://github.com/PotcFdk/SteamDiscoveryQueueAutoSkipper/blob/master/SteamDiscoveryQueueAutoSkipper.user.js#L297 shows the request they do to claim an item.
> 
> Does the command for "!claimitem" currently work for Shmup Fest? By this ticket I was believing it was not functional. That referrer or request seems to work for some time now, so less maintenance. :) Either way this offers some other functionality such as the CanClaimItemResponse protobuf request.

!claimitam still works for Shmup Fest, the implementation is almost the same

**Comment by woctezuma** [comment]
> > > **[themojache](/themojache) ** commented [Sep 26, 2023](#issuecomment-1734760426) •
> > 
> Does the command for "!claimitem" currently work for Shmup Fest? By this ticket I was believing it was not functional.

Sorry for the confusion. The command works. It is just that people usually don't know about it and ask, so I went ahead.

**Comment by chr233** [comment]
> > > > **[themojache](/themojache) ** commented [Sep 26, 2023](#issuecomment-1734760426) •
> > 
> > 
> > Does the command for "!claimitem" currently work for Shmup Fest? By this ticket I was believing it was not functional.
> 
> Sorry for the confusion. The command works. It is just that people usually don't know about it and ask, so I went ahead.
> 
> Related:
> 
> * [Get items from the Strategy Fest 2023 #142](https://github.com/chr233/ASFEnhance/issues/142)
> * [Get items from the Visual Novel Fest 2023 #140](https://github.com/chr233/ASFEnhance/issues/140)
> * [Get items from the Steam Summer Sale 2023 - Daily Trading Card & Sticker #120](https://github.com/chr233/ASFEnhance/issues/120)
> * [Get items from the Sports Fest 2023 #110](https://github.com/chr233/ASFEnhance/issues/110)

maybe post in Discussions is better
