### ISSUE TITLE
Problem with translation

### ISSUE THREAD

**Issue by Rekandy** [chr233/ASFEnhance#154]
Hi, I'm doing a Russian translation and I noticed a discrepancy.

![from Langs.ru-RUJ](https://github.com/chr233/ASFEnhance/assets/77551516/14a224eb-f37b-49e9-9dec-515216589f74)
![from README.en.md](https://github.com/chr233/ASFEnhance/assets/77551516/4ac56f49-c25b-4472-ad30-293e4b26de97)

so can you tell me which one is right?

**Comment by chr233** [comment]
the Readme.md is right, built-in document maybe out date
