### ISSUE TITLE
How about adding a plugin to ASFEnhance that shows account email information

### ISSUE THREAD

**Issue by Rekandy** [chr233/ASFEnhance#159]
such a plugin [already exists](https://github.com/ezhevita/GetEmail) and adding it to ASFEnhanse will not be difficult

**Comment by LittleFreak** [comment]
Makes sense, but might also already be implemented in the main software, since ArchiSteamFarm already supports the steam guard (email and 2FA-Code).
Im not sure at this point, haven't been enough into the wiki translation yet.
Do you have any thoughts about that? @JustArchiNET
