### ISSUE TITLE
Add a command to receive the Steam Awards Nomination Committee 2023 badge

### ISSUE THREAD

**Issue by Rekandy** [chr233/ASFEnhance#166]
Add a command to receive the [Steam Awards Nomination Committee 2023 badge](https://store.steampowered.com/steamawards/nominations)
![steamwebhelper_NIpVwPjMWa](https://github.com/chr233/ASFEnhance/assets/77551516/48a65a56-4903-4211-902c-efc6a2a14023)
![chrome_hHtZA7uvpQ](https://github.com/chr233/ASFEnhance/assets/77551516/c8f0dd91-8fd4-43bd-8d00-6684120f9d21)

**Comment by woctezuma** [comment]
Related:
- #35 
- #164

**Comment by Rekandy** [comment]
Related:
 
 * [steam awards badge #35](https://github.com/chr233/ASFEnhance/issues/35)
 * [Steam Awards #164](https://github.com/chr233/ASFEnhance/discussions/164)

sorry forgot check [Discussions](https://github.com/chr233/ASFEnhance/discussions)

**Comment by woctezuma** [comment]
No problem, I think this fits in the issues, because the command is not in the current build (though it was in the past).

**Comment by woctezuma** [comment]
Apparently, done.
