### ISSUE TITLE
!VOTE only works for the first bot

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#167]
I have tried to vote for the 11 nominations:
```bash
!vote ASF 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2225070
```
I can [see](https://store.steampowered.com/steamawards/nominations/76561198028705366?k=2206531303751302320) that the appIDs are correctly understood for the first bot. **However, the command only works for the first bot!**

```
>> !vote ASF 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2225070

<MainBot> Nominate at least 1 game: √
Nominate a game in each category: √
Play a game you nominated: √
Review or update your review of a game you nominated: √
```

```
>> !checkvote ASF

<MainBot> Nominate at least 1 game: √
Nominate a game in each category: √
Play a game you nominated: √
Review or update your review of a game you nominated: √

<AltBot1> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×

<AltBot2> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×

<AltBot3> Nominate at least 1 game: ×
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
```

**Comment by Botan626** [comment]
and it doesn't vote in these categories:
![image](https://github.com/chr233/ASFEnhance/assets/28785698/a5777491-ce4e-400a-b11c-85568f5ea59d)
![image](https://github.com/chr233/ASFEnhance/assets/28785698/260c4506-3a2c-4bdc-b0c9-de225067ce1c)

**Comment by chr233** [comment]
maybe reach the steam network limits, thinking for a better solution

**Comment by bolexator** [comment]
> maybe reach the steam network limits, thinking for a better solution

I and others have the same problems. Regardless of network, regardless of country. Nominations are the same everywhere. It doesn't seem to be a problem with the stim network.

**Comment by woctezuma** [comment]
I believe the votes are only cast for the first bot.

Indeed, even if I ask to cast the votes for a single other bot, I get the output for the `MainBot`.

**Comment by pontifezo** [comment]
Plugin votes only in 10 categories, but 11th category "Sit Back and Relax Award" is not voted.

**Comment by reanoff** [comment]
[ASFEnhance 2.0.1.1](https://github.com/chr233/ASFEnhance/releases/tag/2.0.1.1) Pre-release

**Comment by woctezuma** [comment]
It looks like the fix is there:
- https://github.com/Rudokhvist/ASFEnhance/tree/eventfix

**Comment by reanoff** [comment]
Voting does not remain in every category.

**Comment by woctezuma** [comment]
> Voting does not remain in every category.

See https://github.com/chr233/ASFEnhance/pull/168#issuecomment-1823046564

**Comment by woctezuma** [comment]
Fixed with https://github.com/chr233/ASFEnhance/releases/tag/2.0.1.1.

**Comment by reanoff** [comment]
> Fixed with https://github.com/chr233/ASFEnhance/releases/tag/2.0.1.1.

no

**Comment by reanoff** [comment]
!vote 01 1868140,2296380,440,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2108330
<
<01> Nominate at least 1 game: √
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
>
!vote 01 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,2225070
<
<01> Nominate at least 1 game: √
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
>
!vote 01 1868140,2296380,440,531640,1997040,1260320,1977170,1624540,1976950,1817230,2225070
<
<01> Nominate at least 1 game: √
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
>
!vote 91 1868140,2296380,440,531640,1997040,1260320,1977170,1624540,1976950,1817230,2225070
<
<91> Nominate at least 1 game: √
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×
>
!vote 91 1868140,2296380,531640,1997040,1260320,1977170,1624540,1976950,1817230,1976950,2225070
<
<91> Nominate at least 1 game: √
Nominate a game in each category: ×
Play a game you nominated: ×
Review or update your review of a game you nominated: ×

**Comment by woctezuma** [comment]
The issue with the first bot was fixed, but not the rest, hence why I closed this issue.
