### ISSUE TITLE
Schedule claimitem daily

### ISSUE THREAD

**Issue by Nuklon** [chr233/ASFEnhance#175]
**Describe what feature you want / 描述需要加入的新功能**
There are quite often free items to get with the claimitem command that require running this command daily to get all items. Would it be possible to add an option to do this automatically once a day?

**Comment by chr233** [comment]
wip, maybe add in next version

**Comment by azhuge233** [comment]
Before official support is available, this can already be achieved by setting up a cron job (or using Task Scheduler) that sends the `CI [Bots]` command to the ASF API.

**Comment by Nuklon** [comment]
> Before official support is available, this can already be achieved by setting up a cron job (or using Task Scheduler) that sends the `CI [Bots]` command to the ASF API.

Not so easy under Windows.

**Comment by dragonGRaf** [comment]
any news here?

**Comment by azhuge233** [comment]
> Before official support is available, this can already be achieved by setting up a cron job (or using Task Scheduler) that sends the `CI [Bots]` command to the ASF API.

A little more details, you can easily do this using bash or Powershell

bash (Linux or more)
```bash
curl -X POST \
  'http(s)://[your ASF instance domain or IP]/Api/Command' \
  --header 'Authentication: [your ASF IPC Password here]' \
  --header 'Content-Type: application/json' \
  --data-raw '{ "Command": "CI asf" }'
```
PowerShell (Windows)
```powershell
Invoke-WebRequest -Method POST `
  -URI "http(s)://[your ASF instance domain or IP]/Api/Command" `
  -ContentType "application/json" `
  -Headers @{ 'Authentication' = '[your ASF IPC Password here]' } `
  -Body "{ 'Command': 'CI asf' }"
```

Under Linux, create a cron job with `crontab -e` to execute the command periodically (or save it as a script).
Windows also comes with a [Task Scheduler](https://en.wikipedia.org/wiki/Windows_Task_Scheduler) can do the same job as cron.

**Comment by chr233** [comment]
added, ASFEnhance will execute `CLAIMITEM` for bots which set `AutoSteamSaleEvent` to `true`, every 8 hours, after 2.0.8.0

**Comment by psy0ch** [comment]
I assume `AutoSteamSaleEvent` was made into `AutoClaimItemBotNames` ? 
Unfortunately there is no Steam Sale up so that I could check if it is working, but thank you for the added functionality!

**Comment by chr233** [comment]
> I assume `AutoSteamSaleEvent` was made into `AutoClaimItemBotNames` ? Unfortunately there is no Steam Sale up so that I could check if it is working, but thank you for the added functionality!

nope, `AutoSteamSaleEvent `  now don't work for ASFEnhance, use `AutoClaimItemBotNames` to control which bot to enable this future

**Comment by visualwind** [comment]
> > I assume `AutoSteamSaleEvent` was made into `AutoClaimItemBotNames` ? Unfortunately there is no Steam Sale up so that I could check if it is working, but thank you for the added functionality!
> 
> nope, `AutoSteamSaleEvent ` now don't work for ASFEnhance, use `AutoClaimItemBotNames` to control which bot to enable this future

请问具体怎么设置asf.json啊。如果我有连个bot：0和1，是写`"AutoClaimItemBotNames": "0,1"`吗？为甚你的示例里，后边又接了两个address?一个Address，一个Addresses

**Comment by chr233** [comment]
> > > I assume `AutoSteamSaleEvent` was made into `AutoClaimItemBotNames` ? Unfortunately there is no Steam Sale up so that I could check if it is working, but thank you for the added functionality!
> > 
> > nope, `AutoSteamSaleEvent ` now don't work for ASFEnhance, use `AutoClaimItemBotNames` to control which bot to enable this future
> 
> 请问具体怎么设置asf.json啊。如果我有连个bot：0和1，是写`"AutoClaimItemBotNames": "0,1"`吗？

是的
