### ISSUE TITLE
这个列表能外置就好了

### ISSUE THREAD

**Issue by SekiBetu** [chr233/ASFEnhance#19]
https://github.com/chr233/ASFEnhance/blob/master/ASFEnhance/Event/DemosDB.cs
![image](https://user-images.githubusercontent.com/38283893/174492572-4e20afc1-c4af-4515-bf49-87daca2797e3.png)
一半的时候突然出错了，然后再运行就要重头开始了，来不及了，明天活动就结束了

**Comment by SekiBetu** [comment]
https://github.com/TcNobo/TcNo-Mass-Steam-Idler/discussions/1
没事了，还是这个好，中断了有记录，可以继续挂

**Comment by chr233** [comment]
其实可以继续运行，会检查Demo是否已经入库

**Comment by SekiBetu** [comment]
> 其实可以继续运行，会检查Demo是否已经入库

没事，他这个更好，运行的时候瞬间检查重复游戏，然后筛选完再运行剩下的，我1201个的列表，运行瞬间自动变成600个了，其他都重复了被他筛选掉了

**Comment by SekiBetu** [comment]
升到1028级了，可惜坛子里这个最全的id不是demo的id，不能和目前的列表去重，不知道咋转换也没时间转换了，今晚结束，就这样了 https://keylol.com/t819944-1-1
