### ISSUE TITLE
Vote for the final round of the Steam Awards

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#191]
We have commands to get free stuff during the Winter sales:
- https://github.com/chr233/ASFEnhance/discussions/190

Every day: 🆓🔁
```
!ex ASF
!ci ASF
```

Once: 🆓
```
!al ASF 981318
```

However, I am not sure whether we have the command to vote **for the final round**:
- https://store.steampowered.com/steamawards

**Maybe a new `!vote ASF` command for this event would be feasible.**

Related:
- #56

**Comment by chr233** [comment]
added in 2.0.6.0, use `VOTE` or `CHECKVOTE`

**Comment by woctezuma** [comment]
Not sure if it works. I get "unknown command".

**Comment by woctezuma** [comment]
Nevermind, it works with `!checkvote ASF` and `!cv ASF`. Specifying the bot names is required, that is all.
