### ISSUE TITLE
EXPLORER

### ISSUE THREAD

**Issue by qirieshkaclwn** [chr233/ASFEnhance#195]
- 原始消息: EXPLORER asf
 - Access: Owner
 - ASF 版本: last
 - 插件版本: last
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": true
}
the plugin does not view the list, the function only worked on 1 account

**Comment by qirieshkaclwn** [comment]
i am retard

**Comment by d1ret** [comment]
idk, but bots doesn't getting cards :(

**Comment by d1ret** [comment]
Ты пофиксил это?

Я так понял при юзании эксплорера у тебя тоже не забирает карты? Но при этом если зайти вручную на акк ,то карта даётся?

**Comment by reanoff** [comment]
It doesn't collect from me

**Comment by woctezuma** [comment]
It works fine for me on **unlimited** bot accounts.

Make sure the cards have not been automatically forwarded to your main account before you noticed.

**Comment by reanoff** [comment]
> У меня это отлично работает с **неограниченным** количеством учетных записей ботов.
> 
> Убедитесь, что карты не были автоматически перенаправлены на ваш основной аккаунт до того, как вы заметили.

does not work

**Comment by reanoff** [comment]
<MASTER> Explore discovery queue task will start immediately
 But the cards don't fall out

**Comment by reanoff** [comment]
When manually, the card will drop out
![image](https://github.com/chr233/ASFEnhance/assets/111295511/388300a6-4567-49b3-aeda-7b14f257db91)

**Comment by d1ret** [comment]
same

**Comment by Botan626** [comment]
most likely ASF needs some changes and then `ex asf` will work

**Comment by Botan626** [comment]
> It works fine for me on **unlimited** bot accounts.
> 
> Make sure the cards have not been automatically forwarded to your main account before you noticed.

`ex asf` worked after I logged in Steam and opened this page https://store.steampowered.com/explore/
![image](https://github.com/chr233/ASFEnhance/assets/28785698/1ff17c85-4aac-43a7-94f8-bba66cfc42f6)

**Comment by chr233** [comment]
see ASF's manual https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#autosteamsaleevent

what this command actually do is reset the ASF's timer.

**Comment by CrazyGhostRider** [comment]
Yes. Does not work.

**Comment by Unriot** [comment]
same, whats gonna be wrong?

**Comment by woctezuma** [comment]
Do you guys use the latest version of ASF?

**Comment by Unriot** [comment]
> Do you guys use the latest version of ASF?

yeah sure

**Comment by chr233** [comment]
This bug has a low priority, and I have to do more important work, it will be slow to fix it.

**Comment by qirieshkaclwn** [comment]
у меня была проблема в другом и я её пофиксил но сейчас у меня 
![image](https://github.com/chr233/ASFEnhance/assets/128681984/418f3133-c071-4e18-a9a7-a41fb2eff8ab)

**Comment by qirieshkaclwn** [comment]
пишет что 0 но если собрать вручную то пишет -1 в стим

**Comment by qirieshkaclwn** [comment]
@chr233 can you make a version of the plugin without checking the access card

**Comment by chr233** [comment]
> @chr233 can you make a version of the plugin without checking if the card is available?

not understand what u want, can u explain more?

**Comment by d1ret** [comment]
> @chr233 can you make a version of the plugin without checking if the card is available?

Как   отметил   chr23   -    команда   всего   лишь  сбрасывает  таймер, на    который   ориентируется   ASF.
А    значит,  это     проверку    нужно     убирать   в   самом    ASF

**Comment by chr233** [comment]
what asfenhance do is reset the ASF's timer, the core logic is in the ASF, I cant do that

**Comment by qirieshkaclwn** [comment]
steam says "Today you can get 0 more cards if you continue to view the list of recommendations."
if I register EXPLORER ASF
I'll see it in the console
"Come back tomorrow to earn another card by browsing your Discovery Queue!"
but if you collect it manually, steam will write "Today you can get -1 more cards if you continue to view the list of recommendations." and will issue a card

**Comment by qirieshkaclwn** [comment]
can you remove the check that leads us to "Come back tomorrow and get another card by looking at your discovery queue!"

**Comment by woctezuma** [comment]
> Today you can get -1 more cards

The `-1` is a bit weird, no?

**Comment by darkdroider** [comment]
Same error here.

**Comment by d1ret** [comment]
I fixed it in ASF SteamSaleEvent.cs code :)

**Comment by woctezuma** [comment]
> Is this happening because ASF first checks if the sale card is available?

I see. So the issue stems from the negative number of cards available returned by Steam.

**Comment by Igorelysss** [comment]
This line checks whether the discovery queue is available?
private async Task<bool?> IsDiscoveryQueueAvailable()

**Comment by d1ret** [comment]
> This line checks whether the discovery queue is available? private async Task<bool?> IsDiscoveryQueueAvailable()

Yes.
But I just cut the function call out of "for"

Was:		

for (byte i = 0; (i < MaxSingleQueuesDaily) && Bot.IsConnectedAndLoggedOn && (await IsDiscoveryQueueAvailable().ConfigureAwait(false)).GetValueOrDefault(); i++)

became: 
		
for (byte i = 0; (i < MaxSingleQueuesDaily) && Bot.IsConnectedAndLoggedOn; i++)

**Comment by Igorelysss** [comment]
Thanks

**Comment by chr233** [comment]
honestly, this works fine in my environment
