### ISSUE TITLE
Get error "tooltip = 社区贡献者" (community badge?)

### ISSUE THREAD

**Issue by bullik01** [chr233/ASFEnhance#2]
Hi again!

I get the next error, but I have already community badge on this account. What i do wrong?
`2021-06-27 14:47:37|ArchiSteamFarm-21338|ERROR|Mark|GetSummerBadge() tooltip = 社区贡献者`

Command used:
`!event 1,1,2,2,2,2,2,2,2,2,1,2,2,1`

Link to account - https://steamcommunity.com/id/MarkSmersh

**Comment by bullik01** [comment]
After 11 mins of executing this command, i get the same error in log and get response in chat:
`读取夏促徽章出错`

**Comment by bullik01** [comment]
Using 1.5.1 (non-fix, fix version disappear from releases section) of plugin

**Comment by bullik01** [comment]
And other like this:

`2021-06-27 15:05:00|ArchiSteamFarm-21338|ERROR|angel28|GetSummerBadge() tooltip = 社区支柱<
2021-06-27 15:05:08|ArchiSteamFarm-21338|ERROR|angel3|GetSummerBadge() tooltip = 收藏代理人

2021-06-27 15:05:25|ArchiSteamFarm-21338|ERROR|angel30|GetSummerBadge() tooltip = 社区大使<
2021-06-27 15:05:33|ArchiSteamFarm-21338|ERROR|angel32|GetSummerBadge() tooltip = 社区支柱<
2021-06-27 15:05:41|ArchiSteamFarm-21338|ERROR|angel35|GetSummerBadge() tooltip = 收藏代理人
2021-06-27 15:05:49|ArchiSteamFarm-21338|ERROR|angel36|GetSummerBadge() tooltip = 收藏代理人
2021-06-27 15:05:57|ArchiSteamFarm-21338|ERROR|angel37|GetSummerBadge() tooltip = 社区支柱<
`

Try translate = Community badges states check?

**Comment by chr233** [comment]
> After 11 mins of executing this command, i get the same error in log and get response in chat:
> `读取夏促徽章出错`

The plugin will check the first badge twice, if the badge's name isn't match any of the five badges, it will log as a warning, and it doesn't affect to core functions, just focus on the command's output.

**Comment by bullik01** [comment]
> > After 11 mins of executing this command, i get the same error in log and get response in chat:
> > `读取夏促徽章出错`
> 
> The plugin will check the first badge twice, if the badge's name isn't match any of the five badges, it will log as a warning, and it doesn't affect to core functions, just focus on the command's output.

But why after finishing of command executing i don't get on account Event Badge?

Anyway - thanks for this great plugin!

**Comment by chr233** [comment]
> And other like this:
> 
> `2021-06-27 15:05:00|ArchiSteamFarm-21338|ERROR|angel28|GetSummerBadge() tooltip = 社区支柱<
> 2021-06-27 15:05:08|ArchiSteamFarm-21338|ERROR|angel3|GetSummerBadge() tooltip = 收藏代理人
> 
> 2021-06-27 15:05:25|ArchiSteamFarm-21338|ERROR|angel30|GetSummerBadge() tooltip = 社区大使<
> 2021-06-27 15:05:33|ArchiSteamFarm-21338|ERROR|angel32|GetSummerBadge() tooltip = 社区支柱<
> 2021-06-27 15:05:41|ArchiSteamFarm-21338|ERROR|angel35|GetSummerBadge() tooltip = 收藏代理人
> 2021-06-27 15:05:49|ArchiSteamFarm-21338|ERROR|angel36|GetSummerBadge() tooltip = 收藏代理人
> 2021-06-27 15:05:57|ArchiSteamFarm-21338|ERROR|angel37|GetSummerBadge() tooltip = 社区支柱<
> `
> 
> Try translate = Community badges states check?

May be the cookies are expired, 

> > > After 11 mins of executing this command, i get the same error in log and get response in chat:
> > > `读取夏促徽章出错`
> > 
> > 
> > The plugin will check the first badge twice, if the badge's name isn't match any of the five badges, it will log as a warning, and it doesn't affect to core functions, just focus on the command's output.
> 
> But why after finishing of command executing i don't get on account Event Badge?
> 
> Anyway - thanks for this great plugin!
> 
> Maybe you can reupload fixed version?

maybe soething went wrong 😅,I tested yesterday for 16 bots, and looks like all fine

**Comment by bullik01** [comment]
> maybe soething went wrong 😅,I tested yesterday for 16 bots, and looks like all fine

Maybe you can reupload fixed version?

I have 685+ bots

**Comment by chr233** [comment]
> > maybe soething went wrong 😅,I tested yesterday for 16 bots, and looks like all fine
> 
> Maybe you can reupload fixed version?
> 
> I have 685+ bots

I think the steam's server maybe have some problem, maybe you can try this later

![image](https://user-images.githubusercontent.com/13798576/123548261-a1875800-d796-11eb-9b5a-e75ec9867864.png)

![image](https://user-images.githubusercontent.com/13798576/123548351-06db4900-d797-11eb-8f88-76a8c48881b1.png)

**Comment by chr233** [comment]
It looks like the plugin can't get the response from the steam store.

**Comment by bullik01** [comment]
OK. I'll try even closer to the night. Thanks a lot!
