### ISSUE TITLE
Get items from the Capitalism and Economy Fest 2023

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#202]
This is different from the usual `!ci ASF` as the items are free in the points shop:
- https://store.steampowered.com/points/shop/app/2771880

without any button to click on the page of the Fest itself:
- https://store.steampowered.com/category/capitalism_economy

**Comment by chr233** [comment]
added in 2.0.10.0, use `REDEEMPOINTSITEM [Bots] 260628,260626,260627` to claim

**Comment by woctezuma** [comment]
Thank you!

```bash
!rpi ASF 260626,260627,260628
```
