### ISSUE TITLE
Unable to get items from the "Steam Pirates vs. Ninjas Fest"

### ISSUE THREAD

**Issue by felipe19930** [chr233/ASFEnhance#204]
**Describe what feature you want / 描述需要加入的新功能**

There's a new Steam giveaway in the Points Shop, which is gives you three items for free (2 animated avatars, and 1 animated sticker):

- [Steam Pirates vs. Ninjas Fest](https://store.steampowered.com/points/shop/app/2790810)

I tried the following command:

```
!rpi foo 2790810
<foo> ID: 2790810 | Status: Done
```

The result indicates success, but I checked my inventory and I did not get any of the free items.

Am I doing something wrong here?

**Comment by chr233** [comment]
use defId to redeem, you can find via steamdb https://steamdb.info/app/2790810/communityitems/

**Comment by chr233** [comment]
`rpi botNames 262246,262245,262247`

**Comment by chr233** [comment]
updated doc

**Comment by woctezuma** [comment]
Related:
- #203

**Comment by felipe19930** [comment]
Thank you both so much!
