### ISSUE TITLE
Does it get the Summer Sale event rewards?

### ISSUE THREAD

**Issue by chuvak889** [chr233/ASFEnhance#21]
I see it was updated 5 hours ago, but the release is older than that, and i cannot compile the project (I have no idea how git stuff works).  
I tried compiling with VSCode but it gives errors.  

Will there be a release with the summer event update?  

Edit: Sorry, my bad, i didn't see you mentioned it's not ready yet. I will close this.

**Comment by chr233** [comment]
added, wait for github action finished complie

**Comment by chr233** [comment]
done.

**Comment by chr233** [comment]
> You don't need to compile the plugin yourself. Just get the released .dll file at:
> - https://github.com/chr233/ASFEnhance/releases/tag/1.6.6.621
> 
> Then:
> - run `EVENTTHEME` (and `EVENT`?) to get the Steam3000 cosmetics,
> - run `EXPLORER` **daily** for the trading card (or let ASF do it by itself).
> 


I've configured github's ci and make release is automatic

**Comment by chuvak889** [comment]
Works great, thank you very much
