### ISSUE TITLE
REPLAY [Year] [Bots] (RP)

### ISSUE THREAD

**Issue by 1UNKNOWNAME3** [chr233/ASFEnhance#217]
Please make sure that the REPLAY [Bots] command by default receives 2 icons at once (2022/2023), now if the [Year] argument is not specified, it will only return 2023, which is not very convenient

Now: REPLAY [Bots] = REPLAY **_2023_** [Bots]
I would like to: REPLAY [Bots] = REPLAY **_2022/2023_** [Bots]

**Comment by chr233** [comment]
why not use this command twice :p

**Comment by 1UNKNOWNAME3** [comment]
> why not use this command twice :p

I would like to get both badges at once with one command, but for a specific badge there are already separate commands when there is a large flow of new accounts, because it’s easier to get 2 badges at once with one command than to use 2 different commands twice

**Comment by chr233** [comment]
added in 2.0.13.3

**Comment by Botan626** [comment]
ASFEnhance 2.0.13.3
`replay `gave only 1 link
![image](https://github.com/chr233/ASFEnhance/assets/28785698/ab014c05-36ff-47e8-8bff-6295c94c17bb)
