### ISSUE TITLE
[bug] some commands throw `unknown command`

### ISSUE THREAD

**Issue by JourneyOver** [chr233/ASFEnhance#22]
Not sure if it's just a case of these commands in your readme not being implemented fully or my account being weird or something, but these commands end up giving me a `Unknown command!` message and throwing errors in the log when input into ASF.

The commands are as followed:

`EXPLORER` and `EX` throws:
```
2022-06-24 19:26:13|ArchiSteamFarm-2265|ERROR|ASF|OnBotCommand() System.NullReferenceException: Object reference not set to an instance of an object.
   at ASFEnhance.Explorer.ReflectionHelper.GetPrivateField[T](Object instance, String fieldname)
   at ASFEnhance.Explorer.Command.ResponseExploreDiscoveryQueue(Bot bot)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ArchiSteamFarm.Plugins.PluginsCore.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamID)
```

Was running ASF Version `5.2.7.6` and noticed these commands not working, so thought it might have been a change in a pre-release that made it not work, but I tested on ASF Version `5.2.6.3` and these commands still do not seem to work. so not really sure if it's something wrong on my end or it's just that they are not fully implemented?

This is all running ASFEnhance Version `1.6.6.621`

There are a couple commands that I did not test as they are to do with adding/removing demos/licenses/comments and all the cart commands

**edited out the commands that are now working**

**Comment by woctezuma** [comment]
For me:
- `ASFEHELP` or `EHELP` -> unknown command,
- `HELP` without anything afterwards -> this works fine: the URL of the Wiki is displayed,
- `EXPLORER` and `EX` -> this works fine.

**Comment by woctezuma** [comment]
> @woctezuma you wasn't getting any errors in the actual logs when passing any of the commands?

I use the terminal of Windows, and there is no such error. For instance:

![Explorer](https://i.ibb.co/r53WK0p/2022-06-25-12-51-39.png)

**Comment by chr233** [comment]
If some command returns "unknown commamd" that's because somewhere throws exceptions

**Comment by JourneyOver** [comment]
@chr233 Latest release I can at least confirm that 
`ASFEHELP`/`EHELP`, and `HELP` with command name after no longer throw a `Unknown command` nor throw any errors in the log. `EXPLORER` and `EX` still throw the `Unknown command` and still throws the error I had pasted above for it into the log file (though I suspect that's because you only messed with the `help` stuff in your latest commit)

**Comment by chr233** [comment]
fixed I just put two same key in a dict

**Comment by chr233** [comment]
I will add error handler later

**Comment by wcwj** [comment]
about ex commands

 add   AutoSteamSaleEvent": true,     to  bot json file shoud be ok
