### ISSUE TITLE
PURCHASE error

### ISSUE THREAD

**Issue by OliverTrust** [chr233/ASFEnhance#229]
After update ASF (6.0.0.3), problem with purchase command:

![1](https://github.com/chr233/ASFEnhance/assets/33681835/424e672f-b5c5-4a2d-b57a-b76d7f0082b2)

**Comment by chr233** [comment]
got it

**Comment by woctezuma** [comment]
I have the same issue when simulating a purchase with `!fakepurchase`.

```
<Wok> Purchase failed, "transID" is Null
```

**Comment by woctezuma** [comment]
In my case, the issue arose because of the following bundle which does not exist on the store:
- https://steamdb.info/bundle/38135/

I thought it was weird that it was cheaper than this bundle with the same content:
- https://steamdb.info/bundle/6033/

**Comment by chr233** [comment]
> I have the same issue when simulating a purchase with `!fakepurchase`.
> 
> ```
> <Wok> Purchase failed, "transID" is Null
> ```
> 
> However, there is also an issue when using my web browser.
> 
> > There seems to have been an error initializing or updating your transaction.
> > Please wait a minute and try again or contact support for assistance.
> 
> ![Picture](https://i.imgur.com/He1y7kF.png)

    good news, I can leave the hospital today, but my work computer might dead due to power cut, lol

**Comment by chr233** [comment]
fixed in 2.1.2.0
