### ISSUE TITLE
[feature request] Add command to apply Steam 3000 profile to bot

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#23]
chr233, please consider adding such command

**Comment by SENPAY98K** [comment]
+1

**Comment by chr233** [comment]
this web api sending payload using protobuf and it causing some extra work

**Comment by SENPAY98K** [comment]
Can be per account maybe ! at least to avoid logins to account 😃

**Comment by chr233** [comment]
![image](https://user-images.githubusercontent.com/13798576/175916359-cb1a58fb-e919-47bf-b557-bb79e5360efb.png)

The payload look like this

**Comment by chr233** [comment]
The ASFEnhance will not support this feature (for now)

**Comment by SENPAY98K** [comment]
Great, thanks for the walkthrough

**Comment by Botan626** [comment]
> https://github.com/chr233/ASFEnhance/blob/master/SetSpeciapProfile.py
> 
> To support protobuf is too much work for me, use this script instead, there is no need to login manually, just using accesstoken
> 
> If `ASFEnhance.Devfeature` is enabled, you can use `ACCESSTOKEN` command to dump all bot's accesstoken.
> 
> @Botan626 @SENPAY98K

I added access token in script, launched it from my PC, Python 3.10.0 is installed, script said "done!", but bot's profile didn't change.

**Comment by chr233** [comment]
> 

do your bot account owns that special profile?

**Comment by Botan626** [comment]
> > 
> 
> do your bot's account owns that special profile?

yes

**Comment by chr233** [comment]
> > > 
> > 
> > do your bot's account owns that special profile?
> 
> yes, I can apply it manually

lol

**Comment by Botan626** [comment]
> > > > 
> > > 
> > > 
> > > do your bot's account owns that special profile?
> > 
> > 
> > yes, I can apply it manually
> 
> lol

Why lol? The bot has that special profile in its inventory, I can save it, if I sign in in bot's account.

![image](https://user-images.githubusercontent.com/28785698/177002788-ea1e97f3-ed51-4ef1-8118-e34d848aca64.png)
