### ISSUE TITLE
PUBLISHRECOMMENT fake error

### ISSUE THREAD

**Issue by uraabk** [chr233/ASFEnhance#232]
When publishing a review, an error message appears in the console, but the review is still added to Steam.

![2024-03-15_145635](https://github.com/chr233/ASFEnhance/assets/10533071/67788f16-f5ea-4883-93d9-0eefb3de483f)

ASF (6.0.0.3)
ASFEnhance (2.1.1.1)

**Comment by chr233** [comment]
i have no idea about this issues, request body seems same as using browser

**Comment by uraabk** [comment]
> i have no idea about this issues, request body seems same as using browser

I was able to resolve this issue by removing the "private" from this file.

https://github.com/chr233/ASFEnhance/blob/master/ASFEnhance/Data/RecommendGameResponse.cs

**Comment by chr233** [comment]
yeah，I got it.

trying to add a command to get recommand content
