### ISSUE TITLE
Command Addcartgift 

### ISSUE THREAD

**Issue by Izymiro** [chr233/ASFEnhance#235]
ADDCARTGIFT [Bots] <SubIDs|BundleIDs> SteamId

Hello
does this command work?

**Comment by Izymiro** [comment]
Previously I used the "PCG" command but it is not there now(

**Comment by chr233** [comment]
deleted pcg command in 2.0.15.0，use addcart , addcartgift, editcartgift , purchase, to send gift

**Comment by Izymiro** [comment]
ACG Login1 SubID Login2 
Right?

thank you for help

**Comment by chr233** [comment]
> ACG Login1 SubID Login2 Right?
> 
> thank you for help

ADDCARTGIFT might not work for unknown reason, you'd better use ADDCART, and EDITCARTGIFT to set to gift mode
