### ISSUE TITLE
Add updateplugins command compatibility

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#239]
Make it possible to update ASFEnhance via `updateplugins` command.

https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#commands-1

**Comment by chr233** [comment]
seems this command is used to update ASF's offical plugins, I think it's better not to modify origin ASF's command

**Comment by Botan626** [comment]
> seems this command is used to update ASF's offical plugins, I think it's better not to modify origin ASF's command

no, it's not for offical plugins, please read changelog for 6.0.1.12:
https://github.com/JustArchiNET/ArchiSteamFarm/releases/tag/6.0.1.12

**Comment by chr233** [comment]
got it

**Comment by Botan626** [comment]
more info: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Plugins-development#automatic-updates

**Comment by chr233** [comment]
thank you, I will test when I have time

**Comment by woctezuma** [comment]
The update process loops.

**Comment by Botan626** [comment]
`updateplugins` command updates latest ASFE now too
ASF 6.0.4.1 and ASFE 2.1.8.1

```
2024-06-18 13:28:31|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Checking for new version...
2024-06-18 13:28:32|ArchiSteamFarm-1|INFO|ASF|UpdateASF() Local version: 6.0.4.1 | Remote version: 6.0.4.1
2024-06-18 13:28:32|ArchiSteamFarm-1|INFO|ASF|UpdatePlugins() Checking for plugin updates...
2024-06-18 13:28:32|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Checking update for ASFEnhance plugin...
2024-06-18 13:28:32|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Updating ASFEnhance plugin...
2024-06-18 13:28:33|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASFEnhance 0%...
2024-06-18 13:28:34|ArchiSteamFarm-1|DEBUG|ASF|OnProgressChanged() ASFEnhance 100%...
2024-06-18 13:28:34|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Patching ASF files...
2024-06-18 13:28:34|ArchiSteamFarm-1|INFO|ASF|UpdatePlugin() Updating ASFEnhance plugin has succeeded, the changes will be loaded on the next ASF launch.
```

**Comment by chr233** [comment]
> would be nice if you would get rid of chinese letters here: `[06/18/24, 06:06:55 PM] ArchiSteamFarm-1 INFO ASF > GetTargetReleaseURL() 插件名称: ASFEnhance The plugin is up to date, no need to update`

edit localized text here: https://crowdin.com/project/asfenhance

**Comment by Botan626** [comment]
> > would be nice if you would get rid of chinese letters here: `[06/18/24, 06:06:55 PM] ArchiSteamFarm-1 INFO ASF > GetTargetReleaseURL() 插件名称: ASFEnhance The plugin is up to date, no need to update`
> 
> edit localized text here: https://crowdin.com/project/asfenhance

I found this: https://crowdin.com/editor/asfenhance/12/zhcn-en?view=comfortable#6722
but it doesn't have `插件名称: ASFEnhance` in it
where is it?

**Comment by chr233** [comment]
![image](https://github.com/chr233/ASFEnhance/assets/13798576/1e10fdd2-f8c8-4882-8461-753acd3f0224)

UpdatePluginListItemName

**Comment by Botan626** [comment]
> UpdatePluginListItemName

Where this screenshot was taken from?

**Comment by Botan626** [comment]
Man please
can we get rid of chinese when updating
more of this:
`2024-06-19 20:58:23|ArchiSteamFarm-13964|INFO|ASF|GetTargetReleaseURL() 插件名称: ASFEnhance *可更新*
2024-06-19 20:58:23|ArchiSteamFarm-13964|INFO|ASF|GetTargetReleaseURL() 当前版本: 2.1.8.2 在线版本: 2.1.8.3`

**Comment by chr233** [comment]
> > UpdatePluginListItemName
> 
> Where this screenshot was taken from?

ResXManager, a visual studio extension
https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager

**Comment by chr233** [comment]
> Author

https://crowdin.com/editor/asfenhance/12/zhcn-en?view=comfortable&filter=basic&value=0#7092

**Comment by Botan626** [comment]
> `2024-06-19 20:58:23|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() 插件名称: ASFEnhance _可更新_
> 
> 2024-06-19 20:58:23|ArchiSteamFarm-1|INFO|ASF|GetTargetReleaseURL() 当前版本: 2.1.8.2 在线版本: 2.1.8.3`

Second string I translated, where is the 1st string `插件名称: ASFEnhance _可更新_?`

**Comment by Botan626** [comment]
What about translations?
