### ISSUE TITLE
Free items in the points shop - `Deckbuilders Fest` as 25 March 

### ISSUE THREAD

**Issue by xTCry** [chr233/ASFEnhance#242]
**Free - Valid only from March 25 to April 1**

### Use command

`RPI [Bots] 277395,277396,277397`

### Items

 - `277395` - **Deck Shuffle** <img src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/items/2842700/ccbc39c75dcd4c5606abdf2bfe95b7b0d2b6cfa3.gif" height="90" />
 - `277396` - **Card Flip** <img src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/items/2842700/aab1329b4d3c7a774f1fe99fafc1e1f75a4f05e8.png" height="90" />
 - `277397` - **Deckbuilder Frame** <img src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/items/2842700/4bf94058e2560d3bf1376f41e9d44cf623a3c67d.png" height="90" />

[View more](https://steamdb.info/app/2842700/history/?changeid=U:46915928)

**Comment by woctezuma** [comment]
- https://github.com/chr233/ASFEnhance/discussions/240
