### ISSUE TITLE
Add/remove wishlist always shows as failure even if successful

### ISSUE THREAD

**Issue by diamond-gold** [chr233/ASFEnhance#244]
**Describe the bug / Bug 描述**
Adding/removing wishlist always shows as failure even if successful

`!AW Bot APPID`
`<Bot> ID: APPID | Status: Failure`

**Comment by chr233** [comment]
fixed, see https://github.com/chr233/ASFEnhance/commit/19b2f32ae1b38e07afd321ad1d43208541986955

not released yet, wait ASF's 6.0.1.x released

**Comment by chr233** [comment]
fixed in 2.1.3.0
