### ISSUE TITLE
ASFEnhance v2.1.3.3 can't update with pu command

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#252]
**Describe the bug**

```
[6:55:07 PM]
>
pu
[6:55:08 PM]
<
<ASFE> <ASFE> Missing Method Exception Detected, Use ASF-generic version may help
<ASFE> 检测到 Missing Method Exception 错误, 换成 ASF-generic 版本可能可以修正
==========================================================================
   at ASFEnhance.Update.WebRequest.DownloadRelease(String downloadUrl)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&)
   at ASFEnhance.Update.WebRequest.DownloadRelease(String downloadUrl)
   at ASFEnhance.Update.WebRequest.UpdatePluginFile(String pluginName, Version pluginVersion, String pluginRepo)
   at ArchiSteamFarm.Core.Utilities.InParallel[T](IEnumerable`1 tasks)
   at ASFEnhance.Update.Command.ResponsePluginUpdate(String pluginNames)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
```

**Comment by Botan626** [comment]
smae for v2.1.3.3

**Comment by Botan626** [comment]
`pu` didn't work in v2.1.8.1

**Comment by chr233** [comment]
it requires ASF-generic, unzip functions require trimed method

**Comment by Botan626** [comment]
> it requires ASF-generic, unzip functions require trimed method

then maybe you could disable `pu` command for win-x64 ASF version completely and other versions which don't support it

**Comment by zycboss** [comment]
> it requires ASF-generic, unzip functions require trimed method

Or don't pack them in zip, it is just a single .dll file.

**Comment by chr233** [comment]
> > it requires ASF-generic, unzip functions require trimed method
> 
> Or don't pack them in zip, it is just a single .dll file.

yoy can also use
UPFATEPLUSING stable ASFEnhance

**Comment by gyq180** [comment]
the same error for 2.1.10.4

**Comment by chr233** [comment]
I think it's time to remove this feature, in next version, the `pu` command will be an alias of the `updateplugins` command

**Comment by Botan626** [comment]
Hi,
interesting read for you is from this message and onwards:
https://discord.com/channels/267292556709068800/332735075315744768/1258006252617990164

**Comment by zycboss** [comment]
> > > it requires ASF-generic, unzip functions require trimed method
> > 
> > 
> > Or don't pack them in zip, it is just a single .dll file.
> 
> yoy can also use UPFATEPLUSING stable ASFEnhance

Corrrrection:

`updateplugins stable ASFEnhance`

works

**Comment by chr233** [comment]
fixed, and now pu is alias to updateplugins
