### ISSUE TITLE
Command "ADDFRIEND" dont work with friend code

### ISSUE THREAD

**Issue by pushkinb** [chr233/ASFEnhance#255]
![image](https://github.com/chr233/ASFEnhance/assets/160387754/67588d9d-020f-421e-9896-824ff9e8624b)

**Comment by pushkinb** [comment]
adding friends by link works, but it is useless because after each addition to friends by this link, it changes, so I would like to add friends by the friendship code

**Comment by chr233** [comment]
got it

**Comment by pushkinb** [comment]
sorry, my accounts have a 5$ block

**Comment by chr233** [comment]
> sorry, my accounts have a 5$ block

you can use friend invite link to bypass this limit
