### ISSUE TITLE
does not accept a link to add to a group

### ISSUE THREAD

**Issue by pushkinb** [chr233/ASFEnhance#259]
**Describe the bug / Bug 描述**
Describe what the bug is
简单描述一下是什么 bug

hi, when I use the "join a group" action, it doesn't want to accept my link to the group

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

[log.txt](https://github.com/chr233/ASFEnhance/files/15333907/log.txt)

![image](https://github.com/chr233/ASFEnhance/assets/160387754/40269c0b-e988-4a0a-bf30-15cb77cab659)

```txt
ASFenhance 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 5.4.0.3
 - 插件版本: 1.7.5.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
 - 错误类型: System.Exception
 - 错误消息: Exception of type 'System.Exception' was thrown.
   at ASFEnhance.ASFEnhance.ResponseCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
   at ASFEnhance.ASFEnhance.OnBotCommand(Bot bot, EAccess access, String message, String[] args, UInt64 steamId)
```

**Comment by chr233** [comment]
use JOINGROUP BAJJJJJJJJJ  instead of full url

**Comment by pushkinb** [comment]
thanks you

**Comment by chr233** [comment]
i will let this command to support full url as input
