### ISSUE TITLE
Delete sent offers

### ISSUE THREAD

**Issue by bzn-afk** [chr233/ASFEnhance#269]
It would be nice if you added a command to delete sent trades.
Sometimes it happens that a bot sends trades, but they are not displayed on the receiving account, and as a result, the bot cannot send more trades.

![image](https://github.com/chr233/ASFEnhance/assets/173573963/b4d35837-6f19-44c5-9a79-900c3b87244f)

**Comment by VladozPlay** [comment]
I had the same problem

**Comment by chr233** [comment]
![image](https://github.com/user-attachments/assets/5c902065-d7d4-4927-be90-7d4512b8623d)

added commands to cancel offer in 2.2.3.0 and later
