### ISSUE TITLE
random nickname & avatar

### ISSUE THREAD

**Issue by VladozPlay** [chr233/ASFEnhance#27]
Are you planning to add these features?

https://github.com/Zignixx/ASF-RenamePlugin (not work)
https://github.com/Zignixx/ASF-RandomAvatarPlugin (not work)

**Comment by chr233** [comment]
these features seems useless, but if u can donate me, I am willing to add them in ASFEnhance.

**Comment by VladozPlay** [comment]
> these features seems useless, but if u can donate me, I am willing to add them in ASFEnhance.

how much?

**Comment by molecul** [comment]
Random avatar was added.
Random nickname - still WIP.

**Comment by VladozPlay** [comment]
@molecul thanks!!!

@chr233 update pls "Random avatar was added" ^.^

**Comment by chr233** [comment]
added

**Comment by VladozPlay** [comment]
> added

>> Enter the command: RANDOMGAMEAVATAR arinas
<> Running...
<< <arinas> Network error

![image](https://user-images.githubusercontent.com/18194595/210382804-997d6294-fc88-4e4e-b086-58ce35ba3adc.png)

**Comment by chr233** [comment]
fixed in 1.7.8.0

**Comment by chr233** [comment]
now support custom online image with command `SETAVATAR`
