### ISSUE TITLE
English Translations

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#277]
You asked me to make eng translations: https://github.com/chr233/ASFEnhance/issues/239#issuecomment-2176482743

I did it:
https://crowdin.com/editor/asfenhance/12/zhcn-en?view=comfortable&filter=basic&value=0#7068
https://crowdin.com/editor/asfenhance/12/zhcn-en?view=comfortable&filter=basic&value=0#7090
https://crowdin.com/editor/asfenhance/12/zhcn-en?view=comfortable&filter=basic&value=0#7092

But you don't approve them. Why?

**Comment by chr233** [comment]
I have not reveiced any message from crowdin, I'm sorry

**Comment by chr233** [comment]
give you permission, now you can approve your translations

I'm sorry I cant pay much attaction on managing translations

**Comment by Botan626** [comment]
> give you permission, now you can approve your translations

thanks
