### ISSUE TITLE
points Award

### ISSUE THREAD

**Issue by stickerx** [chr233/ASFEnhance#283]
**Describe what feature you want / 描述需要加入的新功能**
Description of what you want.
描述一下新功能的用途

allRewardsForProfileToTheCheapestRewards
randomReward

 Give reward to specific account from other accounts

https://api.steampowered.com/ILoyaltyRewardsService/GetSummary

https://api.steampowered.com/ILoyaltyRewardsService/AddReaction/

**Comment by chr233** [comment]
I had already wrote a plugin to do this.

**Comment by stickerx** [comment]
> I had already wrote a plugin to do this.

oh  Ty wher i can find her

**Comment by chr233** [comment]
> @chr233 chr233
> Chr
> > I had already wrote a plugin to do this.
> 
> oh  Ty wher i can find her

that plugin is a part of award system (demo: demo.1vmp.com/admin). and currently not ready to be released, donators can ask me for beta version of the plugin

**Comment by chr233** [comment]
published today, see https://github.com/chr233/ASFAwardToolLite/releases
