### ISSUE TITLE
Change output

### ISSUE THREAD

**Issue by Botan626** [chr233/ASFEnhance#286]
If ASFEnhance is up to date, it says this when checking for an update:
`Plugin name: ASFEnhance The plugin is up to date, no need to update`

Please re-write this output in chinese, so it would be like this in english:
`ASFEnhance plugin is up to date, no need to update`

and then I'll translate it in english on crowdin

**Comment by chr233** [comment]
actually, its ASF's output

**Comment by Botan626** [comment]
> actually, its ASF's output

Are you sure?

Archi said it completely comes from ASFE: https://discord.com/channels/267292556709068800/332735075315744768/1258036409382731776

**Comment by chr233** [comment]
![image](https://github.com/chr233/ASFEnhance/assets/13798576/726a60de-d495-4bbe-acf1-49fc1c4a46c4)

deleted self-update logic in 2.1.11.x

**Comment by Botan626** [comment]
> deleted self-update logic in 2.1.11.x, now it will eval the "updateplugins" command

But your self-update logic is still in ASFEnhance 2.1.11.0 right?

**Comment by chr233** [comment]
> > deleted self-update logic in 2.1.11.x, now it will eval the "updateplugins" command
> 
> But your self-update logic is still in ASFEnhance 2.1.11.0 right?

nope, it already gone in 2.1.11.0

**Comment by Botan626** [comment]
> nope, it already gone in 2.1.11.0

Then why when updating ASF still says:
`INFO ASF > GetTargetReleaseURL() Plugin name: ASFEnhance The plugin is up to date, no need to update`

**Comment by chr233** [comment]
GetTargetReleaseURL is implemented by asfenhance, because ASF's default interface can't judge different language version of plugins
"self-update logic" is the download and replace the binary login

**Comment by chr233** [comment]
> The plugin is up to date

this is just a log, does it effect anything?

**Comment by Botan626** [comment]
> this is just a log, does it effect anything?

it doesn't affect anything, but it's bad written and it's hard to read.

Please change it to `ASFEnhance plugin is up to date, no need to update` in chinese.

**Comment by Botan626** [comment]
Now it changed:
`INFO ASF > GetTargetReleaseURL() No update available for ASFEnhance plugin: 2.1.12.0 ≥ 2.1.12.0.`
