### ISSUE TITLE
Add a !appid command

### ISSUE THREAD

**Issue by Bluscream** [chr233/ASFEnhance#287]
**Describe what feature you want / 描述需要加入的新功能**
Would be nice if we had a `!appid <name>` command that spits out the appid for a given game name

**Comment by chr233** [comment]
if you own games, use `!owns game name`
if you don't own games, use `search game name` to search in store

**Comment by Bluscream** [comment]
this is too confusing and also doesn't seem to work?

![opera_9gDbEw9TUV](https://github.com/chr233/ASFEnhance/assets/3318223/108cdc72-02c3-4555-9e59-60f27e5b5e8b)

**Comment by chr233** [comment]
> this is too confusing and also doesn't seem to work?
> 
> ![opera_9gDbEw9TUV](https://private-user-images.githubusercontent.com/3318223/347286439-108cdc72-02c3-4555-9e59-60f27e5b5e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTQ0MjYsIm5iZiI6MTcyMDU5NDEyNiwicGF0aCI6Ii8zMzE4MjIzLzM0NzI4NjQzOS0xMDhjZGM3Mi0wMmMzLTQ1NTUtOWU1OS02MGYyN2U1YjVlOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDY0ODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhjZWIyYmMzZjE0OGQxMzI0ZjQzNWFhYzJjMWVhNzljYjJiNGM3MjBlODk5YWEyMWJkZWRkMmQyZGY2ZWEzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eOcaAIxdUSJvA4L_oKXnA7uYz0dp1dIwVgHSsQ-bn5M)

![image](https://github.com/chr233/ASFEnhance/assets/13798576/a8da7f9a-8c78-4f11-9ade-18897cbf7b38)

**Comment by chr233** [comment]
pls check ASF's wiki first

**Comment by Bluscream** [comment]
It's still inconvinient to have to use two commands and cant use " but whatever i guess...
