### ISSUE TITLE
钱包兑换码的配置地址到底要怎么设置

### ISSUE THREAD

**Issue by cep94** [chr233/ASFEnhance#288]
这是我的ASF.json，ASFEnhance的地址部分是直接按着说明的，但是每次都提示“本次需要提供账单地址, 但是尚未配置可用地址, 无法激活”
{
  "WebProxy": "127.0.0.1:1080",
  "AutoRestart": false,
  "MaxFarmingTime": 20,
  "AutoClaimItemPeriod": 23,
  "ASFEnhance": {
    "EULA": true,
    "Statistic": true,
    "DevFeature": false,
    "DisabledCmds": [
      "foo",
      "bar"
    ],
    "AutoClaimItemBotNames": "ASF",
    "AutoClaimItemPeriod": 23,
    "ApiKey": "",
    "DefaultLanguage": "",
    "CustomGifteeMessage": "",
    "Address": {
      "Address": "Address",
      "City": "City",
      "Country": "US",
      "State": "NE",
      "PostCode": "12345"
    },
    "Addresses": [
      {
        "Address": "Address",
        "City": "City",
        "Country": "US",
        "State": "NE",
        "PostCode": "12345"
      }
    ]
  }
}

**Comment by chr233** [comment]
```json
 {    "Address": "Address",
            "City": "City",
            "Country": "US",
            "State": "NE",
            "PostCode": "12345"
}
```

改成真实的地址，不要照抄示例，address 地址，city 城市， country 国家  state 省  postcode 邮编，改成能通过校验的地址就行了

**Comment by cep94** [comment]
> ```json
>  {    "Address": "Address",
>             "City": "City",
>             "Country": "US",
>             "State": "NE",
>             "PostCode": "12345"
> }
> ```
> 
> 改成真实的地址，不要照抄示例，address 地址，city 城市， country 国家 state 省 postcode 邮编，改成能通过校验的地址就行了

不行，我改成
        "Address": "482 Flanders Boulevard",
        "City": "Portland",
        "Country": "US",
        "State": "OR",
        "PostCode": "97283"
也一样，而且实际上这个钱包码的地址要求不高的，全部填1都行

**Comment by chr233** [comment]
> > ```json
> >  {    "Address": "Address",
> >             "City": "City",
> >             "Country": "US",
> >             "State": "NE",
> >             "PostCode": "12345"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成真实的地址，不要照抄示例，address 地址，city 城市， country 国家 state 省 postcode 邮编，改成能通过校验的地址就行了
> 
> 不行，我改成 "Address": "482 Flanders Boulevard", "City": "Portland", "Country": "US", "State": "OR", "PostCode": "97283" 也一样，而且实际上这个钱包码的地址要求不高的，全部填1都行

不清楚，有空测试一下，可能接口改了

**Comment by cep94** [comment]
> > > ```json
> > >  {    "Address": "Address",
> > >             "City": "City",
> > >             "Country": "US",
> > >             "State": "NE",
> > >             "PostCode": "12345"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 改成真实的地址，不要照抄示例，address 地址，city 城市， country 国家 state 省 postcode 邮编，改成能通过校验的地址就行了
> > 
> > 
> > 不行，我改成 "Address": "482 Flanders Boulevard", "City": "Portland", "Country": "US", "State": "OR", "PostCode": "97283" 也一样，而且实际上这个钱包码的地址要求不高的，全部填1都行
> 
> 不清楚，有空测试一下，可能接口改了

嗯嗯，是有可能，这个地址，也就对邮编有要求，美国的州必须选他有的，其他部分都没有要求，填1也是让过的
![QQ截图20240712081920](https://github.com/user-attachments/assets/1a22af6f-9101-4dc3-8cc7-c59623fbfeba)

**Comment by chr233** [comment]
> > > > ```json
> > > >  {    "Address": "Address",
> > > >             "City": "City",
> > > >             "Country": "US",
> > > >             "State": "NE",
> > > >             "PostCode": "12345"
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 改成真实的地址，不要照抄示例，address 地址，city 城市， country 国家 state 省 postcode 邮编，改成能通过校验的地址就行了
> > > 
> > > 
> > > 不行，我改成 "Address": "482 Flanders Boulevard", "City": "Portland", "Country": "US", "State": "OR", "PostCode": "97283" 也一样，而且实际上这个钱包码的地址要求不高的，全部填1都行
> > 
> > 不清楚，有空测试一下，可能接口改了
> 
> 嗯嗯，是有可能，这个地址，也就对邮编有要求，美国的州必须选他有的，其他部分都没有要求，填1也是让过的
> ![QQ截图20240712081920](https://github.com/user-attachments/assets/1a22af6f-9101-4dc3-8cc7-c59623fbfeba)
> 

方便提供一下需要地址激活的账号给我吗，用附件发到 chr@chrxw.com ，做测试用
