### ISSUE TITLE
Consider providing `GetTargetReleaseAsset()` instead of `GetTargetReleaseURL()` for plugin updates

### ISSUE THREAD

**Issue by JustArchi** [chr233/ASFEnhance#289]
I've noticed that even though you use `IGitHubPluginUpdates`, you still override logic for fetching release URL - based on my overview of the code, this is not needed, you follow exactly the same logic as ASF does, and there is nothing custom in your GitHub repository for that logic to not work.

You can consider deleting whole **[`GetTargetReleaseURL()`](https://github.com/chr233/ASFEnhance/blob/master/ASFEnhance/ASFEnhance.cs#L1248)**, and instead of that, implement **[`GetTargetReleaseAsset()`](https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/ArchiSteamFarm/Plugins/Interfaces/IGitHubPluginUpdates.cs#L108)**. You simply need to use **[this custom logic you have](https://github.com/chr233/ASFEnhance/blob/master/ASFEnhance/Update/WebRequest.cs#L60)** in that function for returning the correct asset out of `releaseAssets` from the input.

Thanks to that, if the general mechanism will ever need updating, you won't have additional work to do. Overriding `GetTargetReleaseURL()` is intended for lower-level access where you have custom logic for finding the release - e.g. you're using GitLab or your own server instead of GitHub, but you don't, so no need to do that.

Of course your usage is correct, so you can as well disregard this notice if you want to - it's just a potential enhancement I've noticed while browsing ASFE code :+1:

**Comment by chr233** [comment]
thank you
