### ISSUE TITLE
[Suggestion] Translation README.md

### ISSUE THREAD

**Issue by bullik01** [chr233/ASFEnhance#3]
Hi!

I can do translation README.md (or other materials) to next languages:

- English
- Russian
- Ukrainian
- Hebrew

**Comment by chr233** [comment]
I can do translation to English, but I have no idea how to support mulit language in the plugin, maybe I will support English in next version.

**Comment by chr233** [comment]
Now added English version of README.md, I am working on support mulit language support

**Comment by bullik01** [comment]
Thanks! If you need my help - tell me
