### ISSUE TITLE
REMOVELICENSE command not working

### ISSUE THREAD

**Issue by Xarond** [chr233/ASFEnhance#303]
Im doing
RL ASF 580526
and then i got
- REMOVELICENSES [Bots] <SubIds> : Remove bot's licenses with the specified subIDs
 * Avilable shortcut: RL

**Comment by chr233** [comment]
this command removed

**Comment by woctezuma** [comment]
> this command removed

Shouldn't this command have been kept? I thought only the command to remove demos was to be removed based on names:
- #158

**Comment by chr233** [comment]
maybe add it back ?

**Comment by woctezuma** [comment]
Yes, I think `removelicenses` can be useful. It is only `removedemos` which is obsolete (and misleading #158 ).

**Comment by chr233** [comment]
added back

**Comment by woctezuma** [comment]
Thanks!
