### ISSUE TITLE
Programm not start with plugin

### ISSUE THREAD

**Issue by pushkinb** [chr233/ASFEnhance#316]
**Describe the bug / Bug 描述**
Describe what the bug is
简单描述一下是什么 bug

![image](https://github.com/user-attachments/assets/3ae84d99-2fd5-466f-baec-5afc3970b5df)

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

```txt
ASFenhance 遇到错误, 日志如下
==========================================
 - 原始消息: TEST
 - Access: Owner
 - ASF 版本: 6.0.6.4 
 - 插件版本: 1.7.5.0
==========================================
{
  "EULA": true,
  "Statistic": true,
  "DevFeature": false
}
==========================================
 - 错误类型: System.Exception
 - 错误消息: Exception of type 'System.Exception' was thrown.
   at System.ModuleHandle.ResolveType(QCallModule, Int32, IntPtr*, Int32, IntPtr*, Int32, ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandle(Int32, RuntimeTypeHandle[], RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, Type[], Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken, MetadataImport& , RuntimeModule, MetadataToken, RuntimeType, Boolean, ListBuilder`1&, RuntimeType& , IRuntimeMethodInfo& , Boolean& )
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1&, RuntimeModule, Int32, RuntimeType, Boolean, ListBuilder`1)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule, Int32, Int32, RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType, RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(Type, Boolean)
   at System.Attribute.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo, Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo, Boolean)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[TAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
```

**Comment by botka4aet** [comment]
Well, it's not bug
ASF just updated so plugin doesn't work

**Comment by chr233** [comment]
not support 6.0.6.4 yet , wait for next release

**Comment by woctezuma** [comment]
It works for me. Make sure to use ASF generic.

**Comment by chr233** [comment]
try use https://github.com/chr233/ASFEnhance/releases/tag/2.2.3.0

**Comment by Yur0K** [comment]
> try use https://github.com/chr233/ASFEnhance/releases/tag/2.2.3.0

same error with this version

**Comment by chr233** [comment]
maybe require ASF-generic

**Comment by Citrinate** [comment]
> maybe require ASF-generic

Had the [same issue](https://github.com/Citrinate/FreePackages/issues/45) with my plugins.  [Here's the changes](https://github.com/Citrinate/FreePackages/commit/3351b5c93a471a358b97401ef2cf42c95afebc16) I needed to make to get things working with non-generic ASF.

**Comment by gyq180** [comment]
> maybe require ASF-generic

Docker version cannot use ASF-generic, so sad.

**Comment by lianggiraffe** [comment]
> try use https://github.com/chr233/ASFEnhance/releases/tag/2.2.3.0

still not working in 6.0.6.4

**Comment by Botan626** [comment]
ASFEnhance 2.2.3.0 doesn't work with ASF-win-arm64 V6.0.6.4.

**Comment by mindryder** [comment]
ASFEnhance 2.2.3.0 doesn't work

**Comment by ilkekaratas** [comment]
same. with docker it fails.

**Comment by chr233** [comment]
> ASFEnhance 2.2.3.0 doesn't work with ASF-win-x64 6.0.6.4

use ASF-generic can fix, not able to let the plugin support normal version

**Comment by StrangePeanut** [comment]
@gyq180
@ilkekaratas

It seems that the Docker tag `:released` includes the generic version of ASF unlike `:latest`, so `:released` is the one we want to use going forward.

https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker#tags

**Comment by Botan626** [comment]
> > ASFEnhance 2.2.3.0 doesn't work with ASF-win-x64 6.0.6.4
> 
> use ASF-generic can fix, not able to let the plugin support the normal version

Do you mean you don't know how to make plugin work with non-generic ASF
or
from now on ASFEnhance can support only generic ASF?

**Comment by chr233** [comment]
> > > ASFEnhance 2.2.3.0 doesn't work with ASF-win-x64 6.0.6.4
> > 
> > 
> > use ASF-generic can fix, not able to let the plugin support the normal version
> 
> Do you mean you don't know how to make plugin work with non-generic ASF or from now on ASFEnhance will support **_only_** generic ASF?

maybe, there is still a lot of work to do through

**Comment by Botan626** [comment]
> maybe, there is still a lot of work to do through

maybe what?

**Comment by chr233** [comment]
> > maybe, there is still a lot of work to do through
> 
> maybe what?

i don't know

**Comment by Zentberk919** [comment]
"2024-09-03 16:06:24|ArchiSteamFarm-17996|ERROR|ASF|Exit() Exiting with 1 error code!"

this is last line on my logs

**Comment by botka4aet** [comment]
Well, plugin works with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.0 and not with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.1
Most changes - droping System.Globalization system

**Comment by chr233** [comment]
> Well, plugin works with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.0 and not with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.1 Most changes - droping System.Globalization system

maybe use Microsoft.CodeAnalysis.ResxSourceGenerator may help, still finding solutions

**Comment by Botan626** [comment]
> > Well, plugin works with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.0 and not with https://github.com/JustArchiNET/ArchiSteamFarm/tree/6.0.6.1 Most changes - droping System.Globalization system
> 
> maybe use Microsoft.CodeAnalysis.ResxSourceGenerator may help, still finding solutions

you can always ask for help on ASF Dsicord: https://discord.com/channels/267292556709068800/536915576682053662

**Comment by JustArchi** [comment]
Changing to resx generator as Citrinate did **[here](https://github.com/Citrinate/FreePackages/commit/3351b5c93a471a358b97401ef2cf42c95afebc16)** should be sufficient for fixing OS-specific ASF.

Nothing bad in doing it in the old (current) way, this is why ASF-generic worked and continues to work, but since ASF changed to resx generator then some crucial parts for supporting the old way got trimmed out.

People should stop using OS-specific builds if they expect custom plugins to work, really.

**Comment by gyq180** [comment]
> @gyq180 @ilkekaratas It seems that the Docker tag `:released` includes the generic version of ASF unlike `:latest`, so `:released` is the one we want to use going forward.
> 
> > Due to the fact that the latest image comes with capability of auto-updates, it includes bare OS with OS-specific linux ASF version, contrary to **all other tags that include OS with .NET runtime and generic ASF version**.
> 
> Source: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker#tags

I don't see any words said that this tag is generic version, thank you anyway.

**Comment by chr233** [comment]
> Changing to resx generator as Citrinate did **[here](https://github.com/Citrinate/FreePackages/commit/3351b5c93a471a358b97401ef2cf42c95afebc16)** should be sufficient for fixing OS-specific ASF.
> 
> Nothing bad in doing it in the old (current) way, this is why ASF-generic worked and continues to work, but since ASF changed to resx generator then some crucial parts for supporting the old way got trimmed out in OS-specific.
> 
> People should stop using OS-specific builds if they expect custom plugins to work, really.

yep, thank you

**Comment by chr233** [comment]
![image](https://github.com/user-attachments/assets/44f4553b-9ae4-4925-8b2c-5514a408b7eb)

merge to ResxSourceGenerator, seems work, use ASFEnhance 2.2.3.1 may fix this
