### ISSUE TITLE
Please make plugin for non-generic version of ASF.

### ISSUE THREAD

**Issue by l0wdig** [chr233/ASFEnhance#317]
After last ASF update plugin not working.

I tried to use ASF-generic version, but when i run ArchiSteamFarm.cmd console open for 1 sec and then close.

Thanks in advance, great plugin.

**Comment by l0wdig** [comment]
Ok i found fix, i downloaded https://dotnet.microsoft.com/en-us/download and now all good.

**Comment by chr233** [comment]
![image](https://github.com/user-attachments/assets/acf7c37c-3a3c-4820-bd06-6dd75bc3978e)

seems work

**Comment by chr233** [comment]
use 2.2.3.1.
