### ISSUE TITLE
Leave group

### ISSUE THREAD

**Issue by maplepy** [chr233/ASFEnhance#33]
When I try leaving a group it says success and doesn't do anything and join your group which I never wanted to do

Can you please not do that ? and is it possible to fix that? thank you

**Comment by maplepy** [comment]
> You need to provide the `groupID` that can be found via `GROUPLIST` command

already did that

**Comment by chr233** [comment]
> > > join your group which I never wanted to do
> > 
> > 
> > ```json
> > {
> >   "ASFEnhance": {
> >     "EULA": false
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Reference: https://github.com/chr233/ASFEnhance/blob/master/README.en.md#global-configuration
> 
> leaving the group should let people decide to leave the group or not though and Eula accepted or not, the leave group command doesn't work

This functions can be easily abused, so I added this limit

**Comment by maplepy** [comment]
For now I just want this feature to work like it's supposed to, that's all i'm asking for

I don't see how that's limiting any abuse

**Comment by chr233** [comment]
It's a bug, and now fixed, if use command with wrong arguments, ASFEnhance will return its usage.
