### ISSUE TITLE
Crash on ASF 6.1

### ISSUE THREAD

**Issue by Nuklon** [chr233/ASFEnhance#339]
ASF crashes soon after start.

**Comment by chr233** [comment]
only support 6.0.8.7

**Comment by chr233** [comment]
use ASFEnhance 2.3.0.0 will fix

**Comment by chr233** [comment]
https://github.com/chr233/ASFEnhance/releases/tag/2.3.0.0

**Comment by chr233** [comment]
> I have a similar issue, even with ASFEnhance @ 2.3.0.0
> 
> I am using the docker version of ASF 6.1.0.1 on linux arm64
> 
> My current fix is to not use this plugin
> 
> **Log**
> Maybe related note: i had the same issue with [Citrinate/FreePackages](https://github.com/Citrinate/FreePackages), specifically this issue: [Citrinate/FreePackages#67 (comment)](https://github.com/Citrinate/FreePackages/issues/67#issue-2670410026) But updating to [FreePackages V1.5.3.0](https://github.com/Citrinate/FreePackages/releases/tag/1.5.3.0) fixed the issue with their plugin for me Here are the changes between the previous version and the latest version: [Citrinate/FreePackages@1.5.2.3...1.5.3.0](https://github.com/Citrinate/FreePackages/compare/1.5.2.3...1.5.3.0) That commit list contains a change that would probably fix my issue:
> 
> ```diff
> namespace FreePackages.IPC {
> -	[Route("Api/FreePackages", Name = nameof(FreePackages))]
> +	[Route("Api/FreePackages")]
> 	public sealed class FreePackagesController : ArchiController {
> ```

lol, fixed
