### ISSUE TITLE
Vote for the first round of the Steam Awards (nominations)

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#340]
I am not sure whether we have a command to vote **for the first round** of the Steam Awards (nominations):
- https://store.steampowered.com/steamawards/nominations

**Maybe a new `!vote ASF` command for this event would be feasible.**

```
!vote ASF
```

Related:
- #191

![Picture](https://i.imgur.com/bZ2HvGo.png)

**Comment by chr233** [comment]
added in 2.2.8.0

**Comment by bolexator** [comment]
Only two passes. Does not play or write a review.

**Comment by woctezuma** [comment]
I will try that to get 3 ticks.

```sh
!vote ASF 2379780,1712350,275850,2727650,2347910,1425350,2570630,1147860,2835570,1497360,1177980

!addlicense ASF a/2570630
!play ASF 2570630

!checkvote ASF
```

**Comment by Gitlenova** [comment]
hi i am newbie
what command that use to review a game

**Comment by Gitlenova** [comment]
then how to do that

**Comment by bolexator** [comment]
> then how to do that

Not yet, manually

**Comment by woctezuma** [comment]
Alright, this works as long as you have enough playtime to write a review.

```py
import requests

BASE_URL = "http://localhost:1242"
TIMEOUT_IN_SECONDS = 3


def publish_review(bot_name: str, app_id: int) -> requests.Response:
    endpoint = "/Api/Recommend/PublishReview/"
    data = {
        "Recommends": [
            {
                "AppId": app_id,
                "RateUp": True,
                "AllowReply": True,
                "ForFree": True,
                "Public": True,
                "Comment": "This is my review for the Steam Awards.",
            },
        ],
    }
    return requests.post(
        url=f"{BASE_URL}{endpoint}{bot_name}",
        json=data,
        timeout=TIMEOUT_IN_SECONDS,
    )


def delete_review(bot_name: str, app_id: int) -> requests.Response:
    endpoint = "/Api/Recommend/DeleteReview/"
    data = {
        "AppIds": [app_id],
    }
    return requests.post(
        url=f"{BASE_URL}{endpoint}{bot_name}",
        json=data,
        timeout=TIMEOUT_IN_SECONDS,
    )


def main() -> None:
    bot_name = "MyBot"
    app_id = 2570630
    publish_review(bot_name, app_id)
    delete_review(bot_name, app_id)


if __name__ == "__main__":
    main()
```

**Comment by bolexator** [comment]
Yes, need at least 30 minutes of the game, then the review is done

**Comment by Gitlenova** [comment]
@woctezuma please how to use this script

**Comment by woctezuma** [comment]
You need Python with requests, ASF properly configured with IPC, and enough playtime to be able to write a review.

**Comment by bolexator** [comment]
> You need Python with `requests`, ASF properly configured with the IPC interface, and enough playtime to be able to write a review.

The standard set of ASF + ASF Enhance is sufficient, by default. Python is not necessary at all. It is necessary that the game has enough played hours. I conducted an experiment yesterday, PLAY command is enough for the selected game, for at least 30 minutes. After that, the PREC command works fine. I didn't register EULA in the config in a special way, but PREC works.

> @woctezuma please how to use this script

It is necessary that the game for which the review is being written has a simulated time of at least 5 minutes. For example, you need to do a review on the DOTA game (AppID 570). Launching the game - PLAY ASF 570. Wait 30 minutes, then you can write a review - PREC ASF +570 SUPER. After the script has worked, it is advisable to delete the review - DREC ASF 570.

**Comment by woctezuma** [comment]
I see. I did not know about `PREC` and `DREC`, because the description mentions a comment or a recommendation instead of a review, so I thought that was something else. 😆 

| Command                                        | Shorthand | Access     | Description                                                                             |
| ---------------------------------------------- | --------- | ---------- | --------------------------------------------------------------------------------------- |
| `PUBLISHRECOMMENT [Bots] <AppIDs> COMMENT`     | `PREC`    | `Master`   | Publish a recommendation for the game/app, `appd` or `+appId` rateUp, `-appId` rateDown |
| `DELETERECOMMENT [Bots] <AppIDs>`              | `DREC`    | `Master`   | Delete a recommendation for the game/app                                                |
