### ISSUE TITLE
Grab stickers with the discovery queue

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#341]
I have typed:
```sh
!ex ASF
```

However, this has not unlocked 3 stickers per run.

I had to manually explore the queue or use the SteamDB browser add-on to skip the queue.
And do it a few times to get the whole collection of **9 stickers**.

- https://store.steampowered.com/explore?dq=widget
- https://steamcommunity.com/my/itemcollection

![Picture](https://i.imgur.com/RKqdrQ3.png)

**Comment by chr233** [comment]
wip

**Comment by chr233** [comment]
added

**Comment by woctezuma** [comment]
Thanks!
