### ISSUE TITLE
2.3.1.0文件的版本号还是2.3.0.1，启动时卡更新循环

### ISSUE THREAD

**Issue by zycboss** [chr233/ASFEnhance#346]
release文件的版本号没改，启动的时候卡插件更新重启loop
![image](https://github.com/user-attachments/assets/417d732c-2e6f-40f0-91ac-806400824124)

> 2024-12-03 16:52:30|ArchiSteamFarm-34|INFO|ASF|UpdateAndRestart() ASF 将每隔 1 周自动检查新版本。
> 2024-12-03 16:52:30|ArchiSteamFarm-34|INFO|ASF|UpdateASF() 正在检查新版本……
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdateASF() 当前版本：6.1.0.2 | 最新版本：6.1.0.2
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdatePlugins() 正在检查插件更新……
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdatePlugin() 正在检查插件 ASFEnhance 的更新……
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdateCleanup() 正在清理更新后过时的文件……
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdateCleanup() 完成！
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|GetTargetReleaseURL() 找到插件 ASFEnhance 从版本 2.3.0.1 到 2.3.1.0 的更新……
> 2024-12-03 16:52:32|ArchiSteamFarm-34|INFO|ASF|UpdatePlugin() 正在更新插件 ASFEnhance……
> 2024-12-03 16:52:34|ArchiSteamFarm-34|DEBUG|ASF|OnProgressChanged() ASFEnhance 0%...
> 2024-12-03 16:52:35|ArchiSteamFarm-34|DEBUG|ASF|OnProgressChanged() ASFEnhance 100%...
> 2024-12-03 16:52:35|ArchiSteamFarm-34|INFO|ASF|UpdatePlugin() 修补 ASF 文件……
> 2024-12-03 16:52:35|ArchiSteamFarm-34|INFO|ASF|UpdatePlugin() 更新插件 ASFEnhance 成功，更改将会在 ASF 下次运行时生效。
> 2024-12-03 16:52:35|ArchiSteamFarm-34|INFO|ASF|RestartOrExit() 正在重新启动……
>

**Comment by chr233** [comment]
还有这种事

**Comment by chr233** [comment]
改好了
