### ISSUE TITLE
REPLAY Badge

### ISSUE THREAD

**Issue by Domjul** [chr233/ASFEnhance#349]
Hello! 

The command 

REPLAY [Year] [Bots]

did not work for the 2024 badge, i get the message 网络错误. 

Thank you for your help!

**Comment by woctezuma** [comment]
Reference:
- https://store.steampowered.com/replay

**Comment by chr233** [comment]
works now

**Comment by DemonAk** [comment]
asf 6.1.0.3 + ASFEnhance 2.3.2.0
still not working, get Network Error

**Comment by Domjul** [comment]
Works for me! Thank you very much Chr223! ❤️

**Comment by chr233** [comment]
> still not working, get Network Error

![image](https://github.com/user-attachments/assets/dd72e667-f32c-4b03-86da-bad4b19a4079)

**Comment by DemonAk** [comment]
![image](https://github.com/user-attachments/assets/26222e28-a88c-4fb8-8974-53a9fd78d954)
Maybe it depends on the region?, mine RU

**Comment by DemonAk** [comment]
I hope what I wrote above will help solve the problem :)

**Comment by DemonAk** [comment]
I found what the problem was
"DefaultLanguage": "en",
replaced to 
"DefaultLanguage": "english",
or
"DefaultLanguage": "russian",
and all works fine

**Comment by chr233** [comment]
> I found what the problem was
> "DefaultLanguage": "en",
> replaced to 
> "DefaultLanguage": "english",
> or
> "DefaultLanguage": "russian",
> and all works fine

lol

**Comment by DemonAk** [comment]
I think it would be better to do this
REPLAY [Bots] [Years]
like
replay bot1 2022, 2023, 2024

**Comment by Hellix3** [comment]
> I found what the problem was "DefaultLanguage": "en", replaced to "DefaultLanguage": "english", or "DefaultLanguage": "russian", and all works fine

Where does this need to be changed?

**Comment by DemonAk** [comment]
> Where does this need to be changed?
asf.json
"ASFEnhance": {
    "EULA": true,
    "Statistic": true,
    "DevFeature": false,
    "DisabledCmds": [
      "foo",
      "bar"
    ],
    "AutoClaimItemBotNames": "",
    "AutoClaimItemPeriod": 23,
    "DefaultLanguage": "english",
    "CustomGifteeMessage": ""
  }
}

**Comment by chr233** [comment]
> > I found what the problem was "DefaultLanguage": "en", replaced to "DefaultLanguage": "english", or "DefaultLanguage": "russian", and all works fine
> 
> Where does this need to be changed?

this could be detected by plugin, most times
it's unnecessary to edit these options

**Comment by psy0ch** [comment]
Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
Still encountering the error for the !replay command sadly

**Comment by chr233** [comment]
> Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> Still encountering the error for the !replay command sadly

do your accounts got VAC banned?

**Comment by psy0ch** [comment]
> > Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> > Still encountering the error for the !replay command sadly
> 
> do your accounts got VAC banned?

no, the bot account is not vac banned or limited in any sort of way. it is also idling games, so it should have data for a replay too

**Comment by chr233** [comment]
> > > Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> > > Still encountering the error for the !replay command sadly
> > 
> > 
> > do your accounts got VAC banned?
> 
> no, the bot account is not vac banned or limited in any sort of way. it is also idling games, so it should have data for a replay too

pls login to these bot's account and try if it can create replay page manually

**Comment by DemonAk** [comment]
> Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> Still encountering the error for the !replay command sadly

enable debug in asf.json
"Debug": true,
and see what happens when you run the replay command
copy link from log.txt file and put in browser and see what it gives
there will be a link of this type:
https://api.steampowered.com/ISaleFeatureService/GetUserYearInReviewShareImage/v1/?access_token={token}&steamid={bot.SteamID}&year={year}&language=**english**
**do not paste this link here** because it contains account details
when i open link in browser i get empty page because the language was "en"
I replaced it with "english" and everything worked, the request was completed and the data appeared on the page

**Comment by chr233** [comment]
> > > Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> > > Still encountering the error for the !replay command sadly
> > 
> > 
> > enable debug in asf.json "Debug": true, and see what happens when you run the **replay** command copy link from log.txt file and put in browser and see what it gives there will be a link of this type: [https://api.steampowered.com/ISaleFeatureService/GetUserYearInReviewShareImage/v1/?access_token={token}&steamid={bot.SteamID}&year={year}&language=](https://api.steampowered.com/ISaleFeatureService/GetUserYearInReviewShareImage/v1/?access_token=%7Btoken%7D&steamid=%7Bbot.SteamID%7D&year=%7Byear%7D&language=) **english** **do not paste this link here** because it contains account details when i open link in browser i get empty page because the language was "en" I replaced it with "english" and everything worked, the request was completed and the data appeared on the page
> 
> Tried this first. The webpage gave me a empty response to a valid request. All the values in the parameters seem to have been set correctly by ASFEnhanced (it did use =english)
> 
> > > > > Adding that option (and removing it) doesn't work on my end and as chr pointed out, it shouldnt be neccessary anyways.
> > > > > Still encountering the error for the !replay command sadly
> > > > 
> > > > 
> > > > do your accounts got VAC banned?
> > > 
> > > 
> > > no, the bot account is not vac banned or limited in any sort of way. it is also idling games, so it should have data for a replay too
> > 
> > 
> > pls login to these bot's account and try if it can create replay page manually
> 
> manually logged in and it worked. unfortunately i dont know whats the difference to suggest a change :(

could send me some accounts to test what's wrong.
