### ISSUE TITLE
Feature: add for all `events` configurable `Delay`

### ISSUE THREAD

**Issue by xTCry** [chr233/ASFEnhance#39]
_This line is missing in many web requests_
https://github.com/chr233/ASFEnhance/commit/b2f0962b57ee09b059fd3589dbdfaf2f30ba91ed#r90873643

I often get an error when executing an event command.
Example:
```
2022-11-23 07:12:22|ArchiSteamFarm-262211|DEBUG|anyAccount|InternalRequest() Unauthorized <- POST https://store.steampowered.com/steamawards/nominategame
2022-11-23 07:12:22|ArchiSteamFarm-262211|WARN|anyAccount|UrlPost() Request failed after 5 attempts!
2022-11-23 07:12:22|ArchiSteamFarm-262211|DEBUG|anyAccount|UrlPost() Request failed: https://store.steampowered.com/steamawards/nominategame
```
It is sometimes possible to nominate _7/11_ applications. Will have to run the command again.
This problem occurs when running on one account, and what can we say about 5 or more...

Therefore, I think it is necessary to **add more configurable delays for web requests**, as is done in ASF.

I repeat, **thank you very much for your work**, and if you can't implement it in the near future, I can create a PR myself, _but next year_.

**Comment by chr233** [comment]
I think you have tons of bots, in this case, you maybe need to exec command in batches

these command is only avilable in a few days, and is just enougth for most users

**Comment by xTCry** [comment]
Let's assume that yes, I have a "ton" of bots. Then what does it make sense for me to "exec command in batches" for them each time, when I can do it in one command (`VOTE ASF`)?

In addition, I described what I have, such an error occurs when I write a command for the first time for ONE bot.
Maybe I have "too fast Internet" that the Steam server blocks me for a lot of spam (for example, 11 requests per second for one post request).


As a result, I have to do this every time:
`VOTE acc_1 123,123,123,32...`
If the answer returned is that not all categories are published, then repeat the request above until this happens.
`VOTE acc_2 321,321,312,31...`
etc.

**Comment by woctezuma** [comment]
You don't have to do it one by one. You can do it in batches:
- stop all the bots,
- start five new bots,
- run the command with "ASF",
- repeat,
