### ISSUE TITLE
[Feature request] Claim Steam Deck raffle sticker

### ISSUE THREAD

**Issue by guihkx** [chr233/ASFEnhance#45]
From here: https://store.steampowered.com/sale/thegameawardssteamdeckdrop2022

**Comment by chr233** [comment]
working on it now

**Comment by chr233** [comment]
https://github.com/chr233/ASFEnhance/releases/tag/1.6.23.0

**Comment by guihkx** [comment]
That was fast, thank you! Just to confirm, it works for me.
