### ISSUE TITLE
1.7.2.0 dll wrong version

### ISSUE THREAD

**Issue by rdavydov** [chr233/ASFEnhance#53]
[1.7.2.0](https://github.com/chr233/ASFEnhance/releases/download/1.7.2.0/ASFEnhance-en-US.zip) dll has wrong version 1.7.1.0

![image](https://user-images.githubusercontent.com/15850461/208632217-62651667-b85d-455c-9181-61282b3f2302.png)

Because of that, `AV & AU` always show that there is a new version, even though the user has the latest.

**Comment by chr233** [comment]
yep，just forget to push the version change, that's a small problem.

I will release new version when the next sale event starts, that's will be fixed then.
