### ISSUE TITLE
winter cards

### ISSUE THREAD

**Issue by klNuno** [chr233/ASFEnhance#56]
can you update for the winter sale? there's the steam award vote thing where you earn cards:
https://store.steampowered.com/steamawards#GameOfTheYear

thanks and have a nice day !

**Comment by chr233** [comment]
https://github.com/chr233/ASFEnhance/discussions/54

Infected with COVID-19, and not able to code now.

**Comment by klNuno** [comment]
i'm so sorry didn't see your message, take care of you man <3

**Comment by chr233** [comment]
added, now I'm going to have a rest.

**Comment by klNuno** [comment]
tysm it worked !
