### ISSUE TITLE
Is there a command to claim the free daily sticker?

### ISSUE THREAD

**Issue by chuvak889** [chr233/ASFEnhance#57]

**Comment by chr233** [comment]
Infected with COVID-19, and not able to code right now, maybe tomorrow.

**Comment by chr233** [comment]
added. fixed bug with my old codes, use `EVENT` in 1.7.4.0  or later version, now I need to take a break

**Comment by SENPAY98K** [comment]
> added. fixed bug with my old codes, use `EVENT` in 1.7.4.0 or later version, now I need to take a break

Stay healthy, and thanks for making it easy for us!

**Comment by chuvak889** [comment]
> added. fixed bug with my old codes, use `EVENT` in 1.7.4.0 or later version, now I need to take a break

Oh damn. Sorry to hear about covid. Wish you the best. Thank you for your work. Very much appreciated.

**Comment by HenkerX64** [comment]
Thank you! Stay healthy
