### ISSUE TITLE
Steam Replay 2022 badge

### ISSUE THREAD

**Issue by Gardemi14** [chr233/ASFEnhance#63]
will there be a command for this badge?

**Comment by woctezuma** [comment]
For context:
- https://store.steampowered.com/replay/
- https://steamdb.info/badge/64/

**Comment by githubhjs** [comment]
我建議可以直接新增一個指令 去瀏覽某一個頁面
VIEWLINK / VL <URL>
可以一勞永逸

**Comment by chr233** [comment]
working on fetching summary pic url of steam reply

**Comment by chr233** [comment]
added
