### ISSUE TITLE
new functions (commands)

### ISSUE THREAD

**Issue by l0wdig** [chr233/ASFEnhance#68]
Additional function in this command - CLEARNOTIFICATION
Please add to make all unread messages as read.

To clear this.
![image](https://user-images.githubusercontent.com/121511829/209701465-58675af0-c637-4a8a-858e-aa1297f046fd.png)

Thanks for this awesome plugin. <3

**Comment by nolddor** [comment]
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#botbehaviour

> 16 - MarkReceivedMessagesAsRead - Will cause ASF to automatically mark all received messages as read.

**Comment by l0wdig** [comment]
> https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#botbehaviour
> 
> > 16 - MarkReceivedMessagesAsRead - Will cause ASF to automatically mark all received messages as read.

I didn't know there is already this option in ASF. Thanks
