### ISSUE TITLE
Command to join a group

### ISSUE THREAD

**Issue by Tristar7** [chr233/ASFEnhance#7]
Something like

joingroup [Bots] \<GroupName\>

**Comment by chr233** [comment]
Now added, I will release a new version few days later

**Comment by Tristar7** [comment]
Looks like the command works, but also says "network error" when using it.

I've also noticed there is another type of groups (Official Group) specifically for games. They follow a different format:

`https://steamcommunity.com/games/10`

to join them works like this

`https://steamcommunity.com/games/10?action=join&sessionID=\%id\%`

**Comment by chr233** [comment]
Got it, that seems a bug.

**Comment by chr233** [comment]
Bug fixed.
