### ISSUE TITLE
[Bug] Overlap of commands for the alias FC

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#73]
The alias `FC` is a shorthand for `FRIENDCODE` and cannot be used as a shorthand for `FOLLOWCURATOR`. See below:

## Profile Commands

| Command                                | Shorthand | Access          | Description                                                                                         |
| -------------------------------------- | --------- | --------------- | --------------------------------------------------------------------------------------------------- |
| `FRIENDCODE [Bots]`                    | `FC`      | `FamilySharing` | Get bot's friend code                                                                               |

## Curator Commands

| Command                          | Shorthand | Access   | Description                      |
| -------------------------------- | --------- | -------- | -------------------------------- |
| `FOLLOWCURATOR [Bots] <ClanIDs>` | `FC`      | `Master` | Follow specified curator         |

**Comment by chr233** [comment]
the document is wrong, the `FOLLOWCURATOR` 's shortcut is `FCU`
