### ISSUE TITLE
[Bug] DECK command return Network Error

### ISSUE THREAD

**Issue by JGSphaela** [chr233/ASFEnhance#75]
**Describe the bug / Bug 描述**
Describe what the bug is
简单描述一下是什么 bug

使用DECK命令时会返回Network Error, 其他活动命令能正常使用。
Windows和Linux环境均有此问题。
![image](https://user-images.githubusercontent.com/39881472/210423904-88b543d3-9583-459a-80f4-0190483cc597.png)

**Error Log / 错误日志**
Please paste the error log of ASFEnhance, for example
请在此粘贴 ASFEnhance 的错误日志, 示例如下

无错误日志

**Comment by chr233** [comment]
this event had ended, and this command will be removed in next version
