### ISSUE TITLE
Alias overlap with another plugin's alias

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#81]
I notice you use `GA` as an alias for `GAMEAVATAR`:

https://github.com/chr233/ASFEnhance/blob/c09d2a6e699517bc10cf969129acbf6fe1a9d3b3/ASFEnhance/Other/CommandHelpData.cs#L220

The issue is that it overlaps with an alias used by [`Citrinate/BoosterManager`](https://github.com/Citrinate/BoosterManager#command-aliases) for `!gems ASF`.

I would suggest to adopt a 3-letter alias for `GAMEAVATAR`, similar to how you used:
- `PFL` for `PROFILELINK`
- `SEA` for `SETAVATAR`
- etc.

https://github.com/chr233/ASFEnhance/blob/c09d2a6e699517bc10cf969129acbf6fe1a9d3b3/ASFEnhance/Other/CommandHelpData.cs#L218
https://github.com/chr233/ASFEnhance/blob/c09d2a6e699517bc10cf969129acbf6fe1a9d3b3/ASFEnhance/Other/CommandHelpData.cs#L221-L222

Maybe `GMA` or `GAV`?

---

Morevoer, I believe aliases should avoid to end with the letter `A` unless it means to broadcast the command to every bot `ASF`.
So I would favor `GAV`.

In total, there are 3 commands which end with the letter `A` without meaning `ASF`:

https://github.com/chr233/ASFEnhance/blob/c09d2a6e699517bc10cf969129acbf6fe1a9d3b3/ASFEnhance/Other/CommandHelpData.cs#L220-L222

Maybe change these to `GAV`, `RGAV`, `SEAV`?

**Comment by chr233** [comment]
i see

**Comment by woctezuma** [comment]
Thank you! This works!

```ASF.json
{
  "ASFEnhance": {
    "DisabledCmds": [
      "ga"
    ]
  }
}
```
