### ISSUE TITLE
Rate a review?

### ISSUE THREAD

**Issue by kozmo47** [chr233/ASFEnhance#9]
Hello, i like this plugin, do you think you can add a command for bots to rate up a game recommendation?

something like

!rateup ASF (or bot1,bot2,bot3) <game id> <user id>

Game reviews's link structure is like https://steamcommunity.com/id/USER/recommended/GAMEID

So i think it could be done

**Comment by chr233** [comment]
That's function can be easily abused, and I will never add that command

**Comment by kozmo47** [comment]
Suit yourself.
There are already websites where you can pay 2$ for hundreds of rate ups, the abusers already have their own scripts, they aren't waiting for ASF plugins.. 
Only common people use ASF. That have 3-4 alternate accounts.
