### ISSUE TITLE
Claim daily stickers for Spring sale

### ISSUE THREAD

**Issue by woctezuma** [chr233/ASFEnhance#90]
The daily stickers are back for the Spring sale (March 16 - March 23).

References:
- #57 (Winter sale)
- https://store.steampowered.com/category/horror (button to claim the sticker)
- https://www.steamcardexchange.net/index.php?gamepage-appid-2354540 (7 stickers)

**Comment by Enissay** [comment]
Thank you for adding all the needed links.
Indeed `EVENT asf|BotName` works fine :-)

**Comment by woctezuma** [comment]
I thought the `EVENT` command had been removed. Did you download an old version of the plugin, e.g. [v1.7.7.0](https://github.com/chr233/ASFEnhance/releases/tag/1.7.7.0)? 🤔

**Comment by Enissay** [comment]
Aha, good point.
Mine is older `<ASFE> ASFEnhance Version 1.7.4.0`

**Comment by woctezuma** [comment]
Thanks! Good to know! I believe this is the first version to support this feature!

**Comment by woctezuma** [comment]
Perfect! This works! 🥳

**Comment by chr233** [comment]
Add this command back to 1.7.16.0

**Comment by woctezuma** [comment]
Thank you! 🎈 🥳
