### ISSUE TITLE
Is CRAFTBADGE working correct?

### ISSUE THREAD

**Issue by OliverTrust** [chr233/ASFEnhance#97]
Is it correct that the `CRAFTBADGE` craft all possible badges from the cards in the inventory until cards run out?
In instructs `Automatically craft craftable badges (one level at once)`

And then I accidentally crafted 30 lvls but want only one lvl))0)

Current version: 1.7.19.1

**Comment by chr233** [comment]
craft every craftable badge for 1 level at once

**Comment by woctezuma** [comment]
Maybe there is confusion between account levels and badge levels.

**Comment by OliverTrust** [comment]
Yea. now I understand it. I think it would be better to make an additional parameter when sending a command how many badges  exactly need to be made

**Comment by chr233** [comment]
> Yea, now I understand it. I think it would be better to make an additional parameter when sending command, how many badges  exactly need to be made

sure this has a huge space to improve this command, but I'm working on something else at this moment

**Comment by woctezuma** [comment]
I think there is a little issue with this function. I have run it several times on the same bot, and I could only craft 3 badge levels out of 5 possible levels. Similarly, on two other bots, only the first badge level out of 2 possible levels.
